
spring:
  application:
    name: resource-service
  redis:
    host: localhost
    port: 6379
server:
  port: 8083

security:
  oauth2:
    resource:
     filter-order: 3
     id: ${spring.application.name}
#     user-info-uri: http://localhost:8082/user

  user:
    password: user


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

