spring:
  application:
    name: MapperApplication
  datasource:
     name: test
     url: jdbc:mysql://127.0.0.1:3306/shiro_db
     username: root
     password: password
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
server:
  port: 4444
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tianlei.dao


