
spring:
  application:
    name: jwt-resource-service
server:
  port: 8083

security:
  oauth2:
    resource:
     filter-order: 3
     id: ${spring.application.name}
  user:
    password: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

