spring:
  application:
    name: gateway
server:
  port: 8081


zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    order:
      path: /order/**
      sensitiveHeaders:
      serviceId: order-service
add-proxy-headers: true

security:
  oauth2:
    client:
        access-token-uri: http://localhost:8080/uaa/oauth/token
        user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
        client-id: webapp
    resource:
        user-info-uri: http://localhost:8080/uaa/user
        prefer-token-info: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/