spring:
  application:
    name: gateway
server:
  port: 8081

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      sensitiveHeaders:
      serviceId: auth-service
    resource-service:
      path: /resource-service/**
      sensitiveHeaders:
      serviceId: resource-service
  add-proxy-headers: true

security:
  oauth2:
    client:
        access-token-uri: http://localhost:8081/auth-service/oauth/token
        user-authorization-uri: http://localhost:8081/auth-service/oauth/authorize
        client-id: webapp
    resource:
        user-info-uri: http://localhost:8080/auth-service/user
        prefer-token-info: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/