package com.jiejing.dao2.stat;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.jiejing.model.CrmInstAbutmentMonthly;
import com.jiejing.model.CrmInstAbutmentMonthlyExample.Criteria;
import com.jiejing.model.CrmInstAbutmentMonthlyExample.Criterion;
import com.jiejing.model.CrmInstAbutmentMonthlyExample;
import java.util.List;
import java.util.Map;

public class CrmInstAbutmentMonthlySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String countByExample(CrmInstAbutmentMonthlyExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("crm_inst_abutment_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String deleteByExample(CrmInstAbutmentMonthlyExample example) {
        BEGIN();
        DELETE_FROM("crm_inst_abutment_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String insertSelective(CrmInstAbutmentMonthly record) {
        BEGIN();
        INSERT_INTO("crm_inst_abutment_monthly");
        
        if (record.getSignYear() != null) {
            VALUES("sign_year", "#{signYear,jdbcType=INTEGER}");
        }
        
        if (record.getSignMonth() != null) {
            VALUES("sign_month", "#{signMonth,jdbcType=INTEGER}");
        }
        
        if (record.getCountSinst() != null) {
            VALUES("count_sinst", "#{countSinst,jdbcType=INTEGER}");
        }
        
        if (record.getSignedMoney() != null) {
            VALUES("signed_money", "#{signedMoney,jdbcType=INTEGER}");
        }
        
        if (record.getCumCountSinst() != null) {
            VALUES("cum_count_sinst", "#{cumCountSinst,jdbcType=INTEGER}");
        }
        
        if (record.getCumSignedMoney() != null) {
            VALUES("cum_signed_money", "#{cumSignedMoney,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String selectByExample(CrmInstAbutmentMonthlyExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("sign_year");
        } else {
            SELECT("sign_year");
        }
        SELECT("sign_month");
        SELECT("count_sinst");
        SELECT("signed_money");
        SELECT("cum_count_sinst");
        SELECT("cum_signed_money");
        FROM("crm_inst_abutment_monthly");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CrmInstAbutmentMonthly record = (CrmInstAbutmentMonthly) parameter.get("record");
        CrmInstAbutmentMonthlyExample example = (CrmInstAbutmentMonthlyExample) parameter.get("example");
        
        BEGIN();
        UPDATE("crm_inst_abutment_monthly");
        
        if (record.getSignYear() != null) {
            SET("sign_year = #{record.signYear,jdbcType=INTEGER}");
        }
        
        if (record.getSignMonth() != null) {
            SET("sign_month = #{record.signMonth,jdbcType=INTEGER}");
        }
        
        if (record.getCountSinst() != null) {
            SET("count_sinst = #{record.countSinst,jdbcType=INTEGER}");
        }
        
        if (record.getSignedMoney() != null) {
            SET("signed_money = #{record.signedMoney,jdbcType=INTEGER}");
        }
        
        if (record.getCumCountSinst() != null) {
            SET("cum_count_sinst = #{record.cumCountSinst,jdbcType=INTEGER}");
        }
        
        if (record.getCumSignedMoney() != null) {
            SET("cum_signed_money = #{record.cumSignedMoney,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("crm_inst_abutment_monthly");
        
        SET("sign_year = #{record.signYear,jdbcType=INTEGER}");
        SET("sign_month = #{record.signMonth,jdbcType=INTEGER}");
        SET("count_sinst = #{record.countSinst,jdbcType=INTEGER}");
        SET("signed_money = #{record.signedMoney,jdbcType=INTEGER}");
        SET("cum_count_sinst = #{record.cumCountSinst,jdbcType=INTEGER}");
        SET("cum_signed_money = #{record.cumSignedMoney,jdbcType=INTEGER}");
        
        CrmInstAbutmentMonthlyExample example = (CrmInstAbutmentMonthlyExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    public String updateByPrimaryKeySelective(CrmInstAbutmentMonthly record) {
        BEGIN();
        UPDATE("crm_inst_abutment_monthly");
        
        if (record.getCountSinst() != null) {
            SET("count_sinst = #{countSinst,jdbcType=INTEGER}");
        }
        
        if (record.getSignedMoney() != null) {
            SET("signed_money = #{signedMoney,jdbcType=INTEGER}");
        }
        
        if (record.getCumCountSinst() != null) {
            SET("cum_count_sinst = #{cumCountSinst,jdbcType=INTEGER}");
        }
        
        if (record.getCumSignedMoney() != null) {
            SET("cum_signed_money = #{cumSignedMoney,jdbcType=INTEGER}");
        }
        
        WHERE("sign_year = #{signYear,jdbcType=INTEGER}");
        WHERE("sign_month = #{signMonth,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_inst_abutment_monthly
     *
     * @mbggenerated Wed Mar 29 16:49:18 CST 2017
     */
    protected void applyWhere(CrmInstAbutmentMonthlyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}