package com.jiejing.dao2.stat;

import com.jiejing.model.DstatFinanExpense;
import com.jiejing.model.DstatFinanExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatFinanExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int countByExample(DstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByExample(DstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int insert(DstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int insertSelective(DstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    List<DstatFinanExpense> selectByExample(DstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    DstatFinanExpense selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatFinanExpense record, @Param("example") DstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatFinanExpense record, @Param("example") DstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DstatFinanExpense record);

    void batchInsert(@Param("items") List<DstatFinanExpense> items);
}