package com.jiejing.dao2.stat;

import com.jiejing.model.DstatStudentDelta;
import com.jiejing.model.DstatStudentDeltaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatStudentDeltaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int countByExample(DstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int deleteByExample(DstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int insert(DstatStudentDelta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int insertSelective(DstatStudentDelta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    List<DstatStudentDelta> selectByExample(DstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatStudentDelta record, @Param("example") DstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_delta
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatStudentDelta record, @Param("example") DstatStudentDeltaExample example);
}