package com.jiejing.dao2.stat;

import com.jiejing.model.DstatFinanEarningActual;
import com.jiejing.model.DstatFinanEarningActualExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DstatFinanEarningActualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int countByExample(DstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int deleteByExample(DstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insert(DstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insertSelective(DstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    List<DstatFinanEarningActual> selectByExample(DstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatFinanEarningActual record, @Param("example") DstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatFinanEarningActual record, @Param("example") DstatFinanEarningActualExample example);


    List<Map> selectGroupByType(@Param("instIds") List<Long> instIds,
                                @Param("day") Date day);

    List<Map> selectGroupBySource(@Param("instIds") List<Long> instIds,
                                  @Param("day") Date day);
}