package com.jiejing.dao2.stat;

import com.jiejing.model.DstatStudentCreatedDistrib;
import com.jiejing.model.DstatStudentCreatedDistribExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatStudentCreatedDistribMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int countByExample(DstatStudentCreatedDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int deleteByExample(DstatStudentCreatedDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int insert(DstatStudentCreatedDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int insertSelective(DstatStudentCreatedDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    List<DstatStudentCreatedDistrib> selectByExample(DstatStudentCreatedDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatStudentCreatedDistrib record, @Param("example") DstatStudentCreatedDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_created_distrib
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatStudentCreatedDistrib record, @Param("example") DstatStudentCreatedDistribExample example);
}