package com.jiejing.dao2.stat;

import com.jiejing.model.DstatStudentLostDistrib;
import com.jiejing.model.DstatStudentLostDistribExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatStudentLostDistribMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int countByExample(DstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int deleteByExample(DstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int insert(DstatStudentLostDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int insertSelective(DstatStudentLostDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    List<DstatStudentLostDistrib> selectByExample(DstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatStudentLostDistrib record, @Param("example") DstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatStudentLostDistrib record, @Param("example") DstatStudentLostDistribExample example);
}