package com.jiejing.dao2.stat;

import com.jiejing.model.DstatFinanEarning;
import com.jiejing.model.DstatFinanEarningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatFinanEarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int countByExample(DstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int deleteByExample(DstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int insert(DstatFinanEarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int insertSelective(DstatFinanEarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    List<DstatFinanEarning> selectByExample(DstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatFinanEarning record, @Param("example") DstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatFinanEarning record, @Param("example") DstatFinanEarningExample example);

    void batchInsert(@Param("items") List<DstatFinanEarning> items);
}