package com.jiejing.dao2.stat;

import com.jiejing.model.DstatTeachingClasshourInst;
import com.jiejing.model.DstatTeachingClasshourInstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatTeachingClasshourInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int countByExample(DstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int deleteByExample(DstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int insert(DstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int insertSelective(DstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    List<DstatTeachingClasshourInst> selectByExample(DstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    DstatTeachingClasshourInst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatTeachingClasshourInst record, @Param("example") DstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatTeachingClasshourInst record, @Param("example") DstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DstatTeachingClasshourInst record);

    void batchInsert(@Param("items") List<DstatTeachingClasshourInst> items);
}