package com.jiejing.dao2.stat;

import com.jiejing.model.DstatTeachingClasshourTeacherDetail;
import com.jiejing.model.DstatTeachingClasshourTeacherDetailExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.jiejing.vo.ClassHourVO;
import org.apache.ibatis.annotations.Param;

public interface DstatTeachingClasshourTeacherDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int countByExample(DstatTeachingClasshourTeacherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int deleteByExample(DstatTeachingClasshourTeacherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int insert(DstatTeachingClasshourTeacherDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int insertSelective(DstatTeachingClasshourTeacherDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    List<DstatTeachingClasshourTeacherDetail> selectByExample(DstatTeachingClasshourTeacherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatTeachingClasshourTeacherDetail record, @Param("example") DstatTeachingClasshourTeacherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_teaching_classhour_teacher_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatTeachingClasshourTeacherDetail record, @Param("example") DstatTeachingClasshourTeacherDetailExample example);

    List<Map> selectListByExampleGroupByCourse(@Param("beginDate") Date beginDate,
                                               @Param("endDate") Date endDate,
                                               @Param("instIds") List<Long> instIds,
                                               @Param("typeList") List<Long> typeList,
                                               @Param("offset") Integer offset,
                                               @Param("limit") Integer limit);

    Long sumClassHourByExample(@Param("beginDate") Date beginDate,
                              @Param("endDate") Date endDate,
                              @Param("instIds") List<Long> instIds,
                              @Param("typeList") List<Long> typeList);

    int countByExampleGroupByCourse(@Param("beginDate") Date beginDate,
                               @Param("endDate") Date endDate,
                               @Param("instIds") List<Long> instIds,
                               @Param("typeList") List<Long> typeList);
}