package com.jiejing.dao2.stat;

import com.jiejing.model.DstatSaleContract;
import com.jiejing.model.DstatSaleContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatSaleContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int countByExample(DstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int deleteByExample(DstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int insert(DstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int insertSelective(DstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    List<DstatSaleContract> selectByExample(DstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatSaleContract record, @Param("example") DstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatSaleContract record, @Param("example") DstatSaleContractExample example);
}