package com.jiejing.dao2.stat;

import com.jiejing.model.DstatSaleContractDetail;
import com.jiejing.model.DstatSaleContractDetailExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DstatSaleContractDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int countByExample(DstatSaleContractDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int deleteByExample(DstatSaleContractDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int insert(DstatSaleContractDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int insertSelective(DstatSaleContractDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    List<DstatSaleContractDetail> selectByExample(DstatSaleContractDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatSaleContractDetail record, @Param("example") DstatSaleContractDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_sale_contract_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatSaleContractDetail record, @Param("example") DstatSaleContractDetailExample example);

    List<DstatSaleContractDetail> groupBySalePageable(@Param("instIds") List<Long> instIds,
                                                      @Param("beginDate") Date beginDate,
                                                      @Param("endDate") Date endDate,
                                                      @Param("offset") Integer offset,
                                                      @Param("limit") Integer limit);

    Integer selectAmount(@Param("instIds") List<Long> instIds,
                         @Param("beginDate") Date beginDate,
                         @Param("endDate") Date endDate);

    Integer selectCount(@Param("instIds") List<Long> instIds,
                        @Param("beginDate") Date beginDate,
                        @Param("endDate") Date endDate);

    Integer countBySale(@Param("instIds") List<Long> instIds,
                        @Param("beginDate") Date beginDate,
                        @Param("endDate") Date endDate);

}