package com.jiejing.dao2.stat;

import com.jiejing.model.DstatFinanEarningDetail;
import com.jiejing.model.DstatFinanEarningDetailExample;
import com.jiejing.vo.EarningItemVO;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface DstatFinanEarningDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int countByExample(DstatFinanEarningDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int deleteByExample(DstatFinanEarningDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int insert(DstatFinanEarningDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int insertSelective(DstatFinanEarningDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    List<DstatFinanEarningDetail> selectByExample(DstatFinanEarningDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DstatFinanEarningDetail record, @Param("example") DstatFinanEarningDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dstat_finan_earning_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DstatFinanEarningDetail record, @Param("example") DstatFinanEarningDetailExample example);

    void batchInsert(@Param("items") List<DstatFinanEarningDetail> items);

    List<EarningItemVO> listDetail(@Param("instId") Long instId, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate, @Param("typeList") List<Integer> typeList, @Param("offset") Integer offset, @Param("limit") Integer limit);

    int countDetail(@Param("instId") Long instId, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate, @Param("typeList") List<Integer> typeList);

    List<EarningItemVO> selectGroupByCoursePageable(@Param(value = "instIds") List<Long> instIds, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate,
                                                    @Param("offset") Integer offset, @Param("limit") Integer limit);

    Long sum(@Param(value = "instIds")List<Long> instIds, @Param("beginDate")Date beginDate, @Param("endDate")Date endDate);
}