package com.jiejing.dao2.stat;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.jiejing.model.InstStats;
import com.jiejing.model.InstStatsExample.Criteria;
import com.jiejing.model.InstStatsExample.Criterion;
import com.jiejing.model.InstStatsExample;
import java.util.List;
import java.util.Map;

public class InstStatsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String countByExample(InstStatsExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("inst_stats");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String deleteByExample(InstStatsExample example) {
        BEGIN();
        DELETE_FROM("inst_stats");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String insertSelective(InstStats record) {
        BEGIN();
        INSERT_INTO("inst_stats");
        
        if (record.getInstName() != null) {
            VALUES("inst_name", "#{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getStudentCount() != null) {
            VALUES("student_count", "#{studentCount,jdbcType=INTEGER}");
        }
        
        if (record.getPotentialStudentCount() != null) {
            VALUES("potential_student_count", "#{potentialStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getCourseCount() != null) {
            VALUES("course_count", "#{courseCount,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherCount() != null) {
            VALUES("teacher_count", "#{teacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getOffTeacherCount() != null) {
            VALUES("off_teacher_count", "#{offTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getClassCount() != null) {
            VALUES("class_count", "#{classCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedStudentCount() != null) {
            VALUES("assigned_student_count", "#{assignedStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedTeacherCount() != null) {
            VALUES("assigned_teacher_count", "#{assignedTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedClassCount() != null) {
            VALUES("assigned_class_count", "#{assignedClassCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedCourseCount() != null) {
            VALUES("assigned_course_count", "#{assignedCourseCount,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountW() != null) {
            VALUES("active_teacher_count_w", "#{activeTeacherCountW,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLw() != null) {
            VALUES("active_teacher_count_lw", "#{activeTeacherCountLw,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLlw() != null) {
            VALUES("active_teacher_count_llw", "#{activeTeacherCountLlw,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent1d() != null) {
            VALUES("incre_student_1d", "#{increStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent1d() != null) {
            VALUES("incre_potential_student_1d", "#{increPotentialStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent7d() != null) {
            VALUES("incre_student_7d", "#{increStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent7d() != null) {
            VALUES("incre_potential_student_7d", "#{increPotentialStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent30d() != null) {
            VALUES("incre_student_30d", "#{increStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent30d() != null) {
            VALUES("incre_potential_student_30d", "#{increPotentialStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract1d() != null) {
            VALUES("new_contract_1d", "#{newContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract1d() != null) {
            VALUES("renew_contract_1d", "#{renewContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getContract1d() != null) {
            VALUES("contract_1d", "#{contract1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit1d() != null) {
            VALUES("new_profit_1d", "#{newProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit1d() != null) {
            VALUES("renew_profit_1d", "#{renewProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit1d() != null) {
            VALUES("profit_1d", "#{profit1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract7d() != null) {
            VALUES("new_contract_7d", "#{newContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract7d() != null) {
            VALUES("renew_contract_7d", "#{renewContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getContract7d() != null) {
            VALUES("contract_7d", "#{contract7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit7d() != null) {
            VALUES("new_profit_7d", "#{newProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit7d() != null) {
            VALUES("renew_profit_7d", "#{renewProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit7d() != null) {
            VALUES("profit_7d", "#{profit7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract30d() != null) {
            VALUES("new_contract_30d", "#{newContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract30d() != null) {
            VALUES("renew_contract_30d", "#{renewContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getContract30d() != null) {
            VALUES("contract_30d", "#{contract30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit30d() != null) {
            VALUES("new_profit_30d", "#{newProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit30d() != null) {
            VALUES("renew_profit_30d", "#{renewProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit30d() != null) {
            VALUES("profit_30d", "#{profit30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract6m() != null) {
            VALUES("new_contract_6m", "#{newContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract6m() != null) {
            VALUES("renew_contract_6m", "#{renewContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getContract6m() != null) {
            VALUES("contract_6m", "#{contract6m,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit6m() != null) {
            VALUES("new_profit_6m", "#{newProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit6m() != null) {
            VALUES("renew_profit_6m", "#{renewProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getProfit6m() != null) {
            VALUES("profit_6m", "#{profit6m,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String selectByExample(InstStatsExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("inst_id");
        } else {
            SELECT("inst_id");
        }
        SELECT("inst_name");
        SELECT("student_count");
        SELECT("potential_student_count");
        SELECT("course_count");
        SELECT("teacher_count");
        SELECT("off_teacher_count");
        SELECT("class_count");
        SELECT("assigned_student_count");
        SELECT("assigned_teacher_count");
        SELECT("assigned_class_count");
        SELECT("assigned_course_count");
        SELECT("active_teacher_count_w");
        SELECT("active_teacher_count_lw");
        SELECT("active_teacher_count_llw");
        SELECT("incre_student_1d");
        SELECT("incre_potential_student_1d");
        SELECT("incre_student_7d");
        SELECT("incre_potential_student_7d");
        SELECT("incre_student_30d");
        SELECT("incre_potential_student_30d");
        SELECT("new_contract_1d");
        SELECT("renew_contract_1d");
        SELECT("contract_1d");
        SELECT("new_profit_1d");
        SELECT("renew_profit_1d");
        SELECT("profit_1d");
        SELECT("new_contract_7d");
        SELECT("renew_contract_7d");
        SELECT("contract_7d");
        SELECT("new_profit_7d");
        SELECT("renew_profit_7d");
        SELECT("profit_7d");
        SELECT("new_contract_30d");
        SELECT("renew_contract_30d");
        SELECT("contract_30d");
        SELECT("new_profit_30d");
        SELECT("renew_profit_30d");
        SELECT("profit_30d");
        SELECT("new_contract_6m");
        SELECT("renew_contract_6m");
        SELECT("contract_6m");
        SELECT("new_profit_6m");
        SELECT("renew_profit_6m");
        SELECT("profit_6m");
        FROM("inst_stats");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return SQL() + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        InstStats record = (InstStats) parameter.get("record");
        InstStatsExample example = (InstStatsExample) parameter.get("example");
        
        BEGIN();
        UPDATE("inst_stats");
        
        if (record.getInstId() != null) {
            SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        }
        
        if (record.getInstName() != null) {
            SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        }
        
        if (record.getStudentCount() != null) {
            SET("student_count = #{record.studentCount,jdbcType=INTEGER}");
        }
        
        if (record.getPotentialStudentCount() != null) {
            SET("potential_student_count = #{record.potentialStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getCourseCount() != null) {
            SET("course_count = #{record.courseCount,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherCount() != null) {
            SET("teacher_count = #{record.teacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getOffTeacherCount() != null) {
            SET("off_teacher_count = #{record.offTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getClassCount() != null) {
            SET("class_count = #{record.classCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedStudentCount() != null) {
            SET("assigned_student_count = #{record.assignedStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedTeacherCount() != null) {
            SET("assigned_teacher_count = #{record.assignedTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedClassCount() != null) {
            SET("assigned_class_count = #{record.assignedClassCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedCourseCount() != null) {
            SET("assigned_course_count = #{record.assignedCourseCount,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountW() != null) {
            SET("active_teacher_count_w = #{record.activeTeacherCountW,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLw() != null) {
            SET("active_teacher_count_lw = #{record.activeTeacherCountLw,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLlw() != null) {
            SET("active_teacher_count_llw = #{record.activeTeacherCountLlw,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent1d() != null) {
            SET("incre_student_1d = #{record.increStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent1d() != null) {
            SET("incre_potential_student_1d = #{record.increPotentialStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent7d() != null) {
            SET("incre_student_7d = #{record.increStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent7d() != null) {
            SET("incre_potential_student_7d = #{record.increPotentialStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent30d() != null) {
            SET("incre_student_30d = #{record.increStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent30d() != null) {
            SET("incre_potential_student_30d = #{record.increPotentialStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract1d() != null) {
            SET("new_contract_1d = #{record.newContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract1d() != null) {
            SET("renew_contract_1d = #{record.renewContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getContract1d() != null) {
            SET("contract_1d = #{record.contract1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit1d() != null) {
            SET("new_profit_1d = #{record.newProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit1d() != null) {
            SET("renew_profit_1d = #{record.renewProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit1d() != null) {
            SET("profit_1d = #{record.profit1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract7d() != null) {
            SET("new_contract_7d = #{record.newContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract7d() != null) {
            SET("renew_contract_7d = #{record.renewContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getContract7d() != null) {
            SET("contract_7d = #{record.contract7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit7d() != null) {
            SET("new_profit_7d = #{record.newProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit7d() != null) {
            SET("renew_profit_7d = #{record.renewProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit7d() != null) {
            SET("profit_7d = #{record.profit7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract30d() != null) {
            SET("new_contract_30d = #{record.newContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract30d() != null) {
            SET("renew_contract_30d = #{record.renewContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getContract30d() != null) {
            SET("contract_30d = #{record.contract30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit30d() != null) {
            SET("new_profit_30d = #{record.newProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit30d() != null) {
            SET("renew_profit_30d = #{record.renewProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit30d() != null) {
            SET("profit_30d = #{record.profit30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract6m() != null) {
            SET("new_contract_6m = #{record.newContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract6m() != null) {
            SET("renew_contract_6m = #{record.renewContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getContract6m() != null) {
            SET("contract_6m = #{record.contract6m,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit6m() != null) {
            SET("new_profit_6m = #{record.newProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit6m() != null) {
            SET("renew_profit_6m = #{record.renewProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getProfit6m() != null) {
            SET("profit_6m = #{record.profit6m,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("inst_stats");
        
        SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        SET("student_count = #{record.studentCount,jdbcType=INTEGER}");
        SET("potential_student_count = #{record.potentialStudentCount,jdbcType=INTEGER}");
        SET("course_count = #{record.courseCount,jdbcType=INTEGER}");
        SET("teacher_count = #{record.teacherCount,jdbcType=INTEGER}");
        SET("off_teacher_count = #{record.offTeacherCount,jdbcType=INTEGER}");
        SET("class_count = #{record.classCount,jdbcType=INTEGER}");
        SET("assigned_student_count = #{record.assignedStudentCount,jdbcType=INTEGER}");
        SET("assigned_teacher_count = #{record.assignedTeacherCount,jdbcType=INTEGER}");
        SET("assigned_class_count = #{record.assignedClassCount,jdbcType=INTEGER}");
        SET("assigned_course_count = #{record.assignedCourseCount,jdbcType=INTEGER}");
        SET("active_teacher_count_w = #{record.activeTeacherCountW,jdbcType=INTEGER}");
        SET("active_teacher_count_lw = #{record.activeTeacherCountLw,jdbcType=INTEGER}");
        SET("active_teacher_count_llw = #{record.activeTeacherCountLlw,jdbcType=INTEGER}");
        SET("incre_student_1d = #{record.increStudent1d,jdbcType=INTEGER}");
        SET("incre_potential_student_1d = #{record.increPotentialStudent1d,jdbcType=INTEGER}");
        SET("incre_student_7d = #{record.increStudent7d,jdbcType=INTEGER}");
        SET("incre_potential_student_7d = #{record.increPotentialStudent7d,jdbcType=INTEGER}");
        SET("incre_student_30d = #{record.increStudent30d,jdbcType=INTEGER}");
        SET("incre_potential_student_30d = #{record.increPotentialStudent30d,jdbcType=INTEGER}");
        SET("new_contract_1d = #{record.newContract1d,jdbcType=INTEGER}");
        SET("renew_contract_1d = #{record.renewContract1d,jdbcType=INTEGER}");
        SET("contract_1d = #{record.contract1d,jdbcType=INTEGER}");
        SET("new_profit_1d = #{record.newProfit1d,jdbcType=INTEGER}");
        SET("renew_profit_1d = #{record.renewProfit1d,jdbcType=INTEGER}");
        SET("profit_1d = #{record.profit1d,jdbcType=INTEGER}");
        SET("new_contract_7d = #{record.newContract7d,jdbcType=INTEGER}");
        SET("renew_contract_7d = #{record.renewContract7d,jdbcType=INTEGER}");
        SET("contract_7d = #{record.contract7d,jdbcType=INTEGER}");
        SET("new_profit_7d = #{record.newProfit7d,jdbcType=INTEGER}");
        SET("renew_profit_7d = #{record.renewProfit7d,jdbcType=INTEGER}");
        SET("profit_7d = #{record.profit7d,jdbcType=INTEGER}");
        SET("new_contract_30d = #{record.newContract30d,jdbcType=INTEGER}");
        SET("renew_contract_30d = #{record.renewContract30d,jdbcType=INTEGER}");
        SET("contract_30d = #{record.contract30d,jdbcType=INTEGER}");
        SET("new_profit_30d = #{record.newProfit30d,jdbcType=INTEGER}");
        SET("renew_profit_30d = #{record.renewProfit30d,jdbcType=INTEGER}");
        SET("profit_30d = #{record.profit30d,jdbcType=INTEGER}");
        SET("new_contract_6m = #{record.newContract6m,jdbcType=INTEGER}");
        SET("renew_contract_6m = #{record.renewContract6m,jdbcType=INTEGER}");
        SET("contract_6m = #{record.contract6m,jdbcType=INTEGER}");
        SET("new_profit_6m = #{record.newProfit6m,jdbcType=INTEGER}");
        SET("renew_profit_6m = #{record.renewProfit6m,jdbcType=INTEGER}");
        SET("profit_6m = #{record.profit6m,jdbcType=INTEGER}");
        
        InstStatsExample example = (InstStatsExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    public String updateByPrimaryKeySelective(InstStats record) {
        BEGIN();
        UPDATE("inst_stats");
        
        if (record.getInstName() != null) {
            SET("inst_name = #{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getStudentCount() != null) {
            SET("student_count = #{studentCount,jdbcType=INTEGER}");
        }
        
        if (record.getPotentialStudentCount() != null) {
            SET("potential_student_count = #{potentialStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getCourseCount() != null) {
            SET("course_count = #{courseCount,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherCount() != null) {
            SET("teacher_count = #{teacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getOffTeacherCount() != null) {
            SET("off_teacher_count = #{offTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getClassCount() != null) {
            SET("class_count = #{classCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedStudentCount() != null) {
            SET("assigned_student_count = #{assignedStudentCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedTeacherCount() != null) {
            SET("assigned_teacher_count = #{assignedTeacherCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedClassCount() != null) {
            SET("assigned_class_count = #{assignedClassCount,jdbcType=INTEGER}");
        }
        
        if (record.getAssignedCourseCount() != null) {
            SET("assigned_course_count = #{assignedCourseCount,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountW() != null) {
            SET("active_teacher_count_w = #{activeTeacherCountW,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLw() != null) {
            SET("active_teacher_count_lw = #{activeTeacherCountLw,jdbcType=INTEGER}");
        }
        
        if (record.getActiveTeacherCountLlw() != null) {
            SET("active_teacher_count_llw = #{activeTeacherCountLlw,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent1d() != null) {
            SET("incre_student_1d = #{increStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent1d() != null) {
            SET("incre_potential_student_1d = #{increPotentialStudent1d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent7d() != null) {
            SET("incre_student_7d = #{increStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent7d() != null) {
            SET("incre_potential_student_7d = #{increPotentialStudent7d,jdbcType=INTEGER}");
        }
        
        if (record.getIncreStudent30d() != null) {
            SET("incre_student_30d = #{increStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getIncrePotentialStudent30d() != null) {
            SET("incre_potential_student_30d = #{increPotentialStudent30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract1d() != null) {
            SET("new_contract_1d = #{newContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract1d() != null) {
            SET("renew_contract_1d = #{renewContract1d,jdbcType=INTEGER}");
        }
        
        if (record.getContract1d() != null) {
            SET("contract_1d = #{contract1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit1d() != null) {
            SET("new_profit_1d = #{newProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit1d() != null) {
            SET("renew_profit_1d = #{renewProfit1d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit1d() != null) {
            SET("profit_1d = #{profit1d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract7d() != null) {
            SET("new_contract_7d = #{newContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract7d() != null) {
            SET("renew_contract_7d = #{renewContract7d,jdbcType=INTEGER}");
        }
        
        if (record.getContract7d() != null) {
            SET("contract_7d = #{contract7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit7d() != null) {
            SET("new_profit_7d = #{newProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit7d() != null) {
            SET("renew_profit_7d = #{renewProfit7d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit7d() != null) {
            SET("profit_7d = #{profit7d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract30d() != null) {
            SET("new_contract_30d = #{newContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract30d() != null) {
            SET("renew_contract_30d = #{renewContract30d,jdbcType=INTEGER}");
        }
        
        if (record.getContract30d() != null) {
            SET("contract_30d = #{contract30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit30d() != null) {
            SET("new_profit_30d = #{newProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit30d() != null) {
            SET("renew_profit_30d = #{renewProfit30d,jdbcType=INTEGER}");
        }
        
        if (record.getProfit30d() != null) {
            SET("profit_30d = #{profit30d,jdbcType=INTEGER}");
        }
        
        if (record.getNewContract6m() != null) {
            SET("new_contract_6m = #{newContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewContract6m() != null) {
            SET("renew_contract_6m = #{renewContract6m,jdbcType=INTEGER}");
        }
        
        if (record.getContract6m() != null) {
            SET("contract_6m = #{contract6m,jdbcType=INTEGER}");
        }
        
        if (record.getNewProfit6m() != null) {
            SET("new_profit_6m = #{newProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getRenewProfit6m() != null) {
            SET("renew_profit_6m = #{renewProfit6m,jdbcType=INTEGER}");
        }
        
        if (record.getProfit6m() != null) {
            SET("profit_6m = #{profit6m,jdbcType=INTEGER}");
        }
        
        WHERE("inst_id = #{instId,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    protected void applyWhere(InstStatsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}