package com.jiejing.dao2.stat;

import com.jiejing.model.InstStudentReferralRateMonthly;
import com.jiejing.model.InstStudentReferralRateMonthlyExample;
import com.jiejing.model.InstStudentReferralRateMonthlyKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstStudentReferralRateMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @SelectProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="countByExample")
    int countByExample(InstStudentReferralRateMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @DeleteProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstStudentReferralRateMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @Delete({
        "delete from inst_student_referral_rate_monthly",
        "where inst_id = #{instId,jdbcType=BIGINT}",
          "and month = #{month,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(InstStudentReferralRateMonthlyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @Insert({
        "insert into inst_student_referral_rate_monthly (inst_id, month, ",
        "referral_count, new_count, ",
        "referral_rate)",
        "values (#{instId,jdbcType=BIGINT}, #{month,jdbcType=INTEGER}, ",
        "#{referralCount,jdbcType=INTEGER}, #{newCount,jdbcType=INTEGER}, ",
        "#{referralRate,jdbcType=DOUBLE})"
    })
    int insert(InstStudentReferralRateMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @InsertProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(InstStudentReferralRateMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @SelectProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="month", property="month", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="referral_count", property="referralCount", jdbcType=JdbcType.INTEGER),
        @Result(column="new_count", property="newCount", jdbcType=JdbcType.INTEGER),
        @Result(column="referral_rate", property="referralRate", jdbcType=JdbcType.DOUBLE)
    })
    List<InstStudentReferralRateMonthly> selectByExample(InstStudentReferralRateMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @Select({
        "select",
        "inst_id, month, referral_count, new_count, referral_rate",
        "from inst_student_referral_rate_monthly",
        "where inst_id = #{instId,jdbcType=BIGINT}",
          "and month = #{month,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="month", property="month", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="referral_count", property="referralCount", jdbcType=JdbcType.INTEGER),
        @Result(column="new_count", property="newCount", jdbcType=JdbcType.INTEGER),
        @Result(column="referral_rate", property="referralRate", jdbcType=JdbcType.DOUBLE)
    })
    InstStudentReferralRateMonthly selectByPrimaryKey(InstStudentReferralRateMonthlyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @UpdateProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstStudentReferralRateMonthly record, @Param("example") InstStudentReferralRateMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @UpdateProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstStudentReferralRateMonthly record, @Param("example") InstStudentReferralRateMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @UpdateProvider(type=InstStudentReferralRateMonthlySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InstStudentReferralRateMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_student_referral_rate_monthly
     *
     * @mbggenerated Mon Apr 24 10:44:03 CST 2017
     */
    @Update({
        "update inst_student_referral_rate_monthly",
        "set referral_count = #{referralCount,jdbcType=INTEGER},",
          "new_count = #{newCount,jdbcType=INTEGER},",
          "referral_rate = #{referralRate,jdbcType=DOUBLE}",
        "where inst_id = #{instId,jdbcType=BIGINT}",
          "and month = #{month,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InstStudentReferralRateMonthly record);
}