package com.jiejing.dao2.stat;

import com.jiejing.model.InstSigninCountersWeekly;
import com.jiejing.model.InstSigninCountersWeeklyExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface InstSigninCountersWeeklyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @SelectProvider(type=InstSigninCountersWeeklySqlProvider.class, method="countByExample")
    int countByExample(InstSigninCountersWeeklyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @DeleteProvider(type=InstSigninCountersWeeklySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstSigninCountersWeeklyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @Delete({
        "delete from inst_signin_counters_weekly",
        "where first_weekday = #{firstWeekday,jdbcType=DATE}"
    })
    int deleteByPrimaryKey(Date firstWeekday);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @Insert({
        "insert into inst_signin_counters_weekly (first_weekday, last_weekday, ",
        "active_teacher_count, active_inst_count)",
        "values (#{firstWeekday,jdbcType=DATE}, #{lastWeekday,jdbcType=DATE}, ",
        "#{activeTeacherCount,jdbcType=INTEGER}, #{activeInstCount,jdbcType=INTEGER})"
    })
    int insert(InstSigninCountersWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @InsertProvider(type=InstSigninCountersWeeklySqlProvider.class, method="insertSelective")
    int insertSelective(InstSigninCountersWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @SelectProvider(type=InstSigninCountersWeeklySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="first_weekday", property="firstWeekday", jdbcType=JdbcType.DATE, id=true),
        @Result(column="last_weekday", property="lastWeekday", jdbcType=JdbcType.DATE),
        @Result(column="active_teacher_count", property="activeTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="active_inst_count", property="activeInstCount", jdbcType=JdbcType.INTEGER)
    })
    List<InstSigninCountersWeekly> selectByExampleWithRowbounds(InstSigninCountersWeeklyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @SelectProvider(type=InstSigninCountersWeeklySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="first_weekday", property="firstWeekday", jdbcType=JdbcType.DATE, id=true),
        @Result(column="last_weekday", property="lastWeekday", jdbcType=JdbcType.DATE),
        @Result(column="active_teacher_count", property="activeTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="active_inst_count", property="activeInstCount", jdbcType=JdbcType.INTEGER)
    })
    List<InstSigninCountersWeekly> selectByExample(InstSigninCountersWeeklyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @Select({
        "select",
        "first_weekday, last_weekday, active_teacher_count, active_inst_count",
        "from inst_signin_counters_weekly",
        "where first_weekday = #{firstWeekday,jdbcType=DATE}"
    })
    @Results({
        @Result(column="first_weekday", property="firstWeekday", jdbcType=JdbcType.DATE, id=true),
        @Result(column="last_weekday", property="lastWeekday", jdbcType=JdbcType.DATE),
        @Result(column="active_teacher_count", property="activeTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="active_inst_count", property="activeInstCount", jdbcType=JdbcType.INTEGER)
    })
    InstSigninCountersWeekly selectByPrimaryKey(Date firstWeekday);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @UpdateProvider(type=InstSigninCountersWeeklySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstSigninCountersWeekly record, @Param("example") InstSigninCountersWeeklyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @UpdateProvider(type=InstSigninCountersWeeklySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstSigninCountersWeekly record, @Param("example") InstSigninCountersWeeklyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @UpdateProvider(type=InstSigninCountersWeeklySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InstSigninCountersWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_signin_counters_weekly
     *
     * @mbggenerated Fri Mar 31 10:34:05 CST 2017
     */
    @Update({
        "update inst_signin_counters_weekly",
        "set last_weekday = #{lastWeekday,jdbcType=DATE},",
          "active_teacher_count = #{activeTeacherCount,jdbcType=INTEGER},",
          "active_inst_count = #{activeInstCount,jdbcType=INTEGER}",
        "where first_weekday = #{firstWeekday,jdbcType=DATE}"
    })
    int updateByPrimaryKey(InstSigninCountersWeekly record);
}