package com.jiejing.dao2.stat;

import com.jiejing.model.InstClassHourCourseTeacherMonthly;
import com.jiejing.model.InstClassHourCourseTeacherMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstClassHourCourseTeacherMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @SelectProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="countByExample")
    int countByExample(InstClassHourCourseTeacherMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @DeleteProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstClassHourCourseTeacherMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @Insert({
        "insert into inst_class_hour_course_teacher_monthly (inst_id, course_id, ",
        "teacher_id, type, class_hour, ",
        "price, month)",
        "values (#{instId,jdbcType=BIGINT}, #{courseId,jdbcType=BIGINT}, ",
        "#{teacherId,jdbcType=BIGINT}, #{type,jdbcType=BIGINT}, #{classHour,jdbcType=BIGINT}, ",
        "#{price,jdbcType=BIGINT}, #{month,jdbcType=BIGINT})"
    })
    int insert(InstClassHourCourseTeacherMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @InsertProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(InstClassHourCourseTeacherMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @SelectProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.BIGINT),
        @Result(column="class_hour", property="classHour", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="month", property="month", jdbcType=JdbcType.BIGINT)
    })
    List<InstClassHourCourseTeacherMonthly> selectByExample(InstClassHourCourseTeacherMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @UpdateProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstClassHourCourseTeacherMonthly record, @Param("example") InstClassHourCourseTeacherMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_monthly
     *
     * @mbggenerated Thu Apr 13 15:15:57 CST 2017
     */
    @UpdateProvider(type=InstClassHourCourseTeacherMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstClassHourCourseTeacherMonthly record, @Param("example") InstClassHourCourseTeacherMonthlyExample example);
}