package com.jiejing.dao2.stat;

import com.jiejing.model.InstTeacherSigninCourseMonthly;
import com.jiejing.model.InstTeacherSigninCourseMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstTeacherSigninCourseMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @SelectProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="countByExample")
    int countByExample(InstTeacherSigninCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @DeleteProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstTeacherSigninCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @Insert({
        "insert into inst_teacher_signin_course_monthly (count, inst_id, ",
        "teacher_id, course_id, ",
        "month, absent_number, ",
        "total_number)",
        "values (#{count,jdbcType=INTEGER}, #{instId,jdbcType=BIGINT}, ",
        "#{teacherId,jdbcType=BIGINT}, #{courseId,jdbcType=BIGINT}, ",
        "#{month,jdbcType=BIGINT}, #{absentNumber,jdbcType=INTEGER}, ",
        "#{totalNumber,jdbcType=INTEGER})"
    })
    int insert(InstTeacherSigninCourseMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @InsertProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(InstTeacherSigninCourseMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @SelectProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="month", property="month", jdbcType=JdbcType.BIGINT),
        @Result(column="absent_number", property="absentNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="total_number", property="totalNumber", jdbcType=JdbcType.INTEGER)
    })
    List<InstTeacherSigninCourseMonthly> selectByExample(InstTeacherSigninCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @UpdateProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstTeacherSigninCourseMonthly record, @Param("example") InstTeacherSigninCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_signin_course_monthly
     *
     * @mbggenerated Wed Apr 19 10:48:19 CST 2017
     */
    @UpdateProvider(type=InstTeacherSigninCourseMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstTeacherSigninCourseMonthly record, @Param("example") InstTeacherSigninCourseMonthlyExample example);
}