package com.jiejing.dao2.stat;

import com.jiejing.model.InstTeacherClassHourCourseMonthly;
import com.jiejing.model.InstTeacherClassHourCourseMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstTeacherClassHourCourseMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @SelectProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="countByExample")
    int countByExample(InstTeacherClassHourCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @DeleteProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstTeacherClassHourCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @Insert({
        "insert into inst_teacher_class_hour_course_monthly (inst_id, course_id, ",
        "teacher_id, type, class_hour, ",
        "month)",
        "values (#{instId,jdbcType=BIGINT}, #{courseId,jdbcType=BIGINT}, ",
        "#{teacherId,jdbcType=BIGINT}, #{type,jdbcType=BIGINT}, #{classHour,jdbcType=BIGINT}, ",
        "#{month,jdbcType=BIGINT})"
    })
    int insert(InstTeacherClassHourCourseMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @InsertProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(InstTeacherClassHourCourseMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @SelectProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.BIGINT),
        @Result(column="class_hour", property="classHour", jdbcType=JdbcType.BIGINT),
        @Result(column="month", property="month", jdbcType=JdbcType.BIGINT)
    })
    List<InstTeacherClassHourCourseMonthly> selectByExample(InstTeacherClassHourCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @UpdateProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstTeacherClassHourCourseMonthly record, @Param("example") InstTeacherClassHourCourseMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_teacher_class_hour_course_monthly
     *
     * @mbggenerated Fri May 05 17:16:19 CST 2017
     */
    @UpdateProvider(type=InstTeacherClassHourCourseMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstTeacherClassHourCourseMonthly record, @Param("example") InstTeacherClassHourCourseMonthlyExample example);
}