package com.jiejing.dao2.stat;

import com.jiejing.model.InstStats;
import com.jiejing.model.InstStatsExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface InstStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @SelectProvider(type=InstStatsSqlProvider.class, method="countByExample")
    int countByExample(InstStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @DeleteProvider(type=InstStatsSqlProvider.class, method="deleteByExample")
    int deleteByExample(InstStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @Delete({
        "delete from inst_stats",
        "where inst_id = #{instId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long instId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @Insert({
        "insert into inst_stats (inst_name, student_count, ",
        "potential_student_count, course_count, ",
        "teacher_count, off_teacher_count, ",
        "class_count, assigned_student_count, ",
        "assigned_teacher_count, assigned_class_count, ",
        "assigned_course_count, active_teacher_count_w, ",
        "active_teacher_count_lw, active_teacher_count_llw, ",
        "incre_student_1d, incre_potential_student_1d, ",
        "incre_student_7d, incre_potential_student_7d, ",
        "incre_student_30d, incre_potential_student_30d, ",
        "new_contract_1d, renew_contract_1d, ",
        "contract_1d, new_profit_1d, ",
        "renew_profit_1d, profit_1d, ",
        "new_contract_7d, renew_contract_7d, ",
        "contract_7d, new_profit_7d, ",
        "renew_profit_7d, profit_7d, ",
        "new_contract_30d, renew_contract_30d, ",
        "contract_30d, new_profit_30d, ",
        "renew_profit_30d, profit_30d, ",
        "new_contract_6m, renew_contract_6m, ",
        "contract_6m, new_profit_6m, ",
        "renew_profit_6m, profit_6m)",
        "values (#{instName,jdbcType=VARCHAR}, #{studentCount,jdbcType=INTEGER}, ",
        "#{potentialStudentCount,jdbcType=INTEGER}, #{courseCount,jdbcType=INTEGER}, ",
        "#{teacherCount,jdbcType=INTEGER}, #{offTeacherCount,jdbcType=INTEGER}, ",
        "#{classCount,jdbcType=INTEGER}, #{assignedStudentCount,jdbcType=INTEGER}, ",
        "#{assignedTeacherCount,jdbcType=INTEGER}, #{assignedClassCount,jdbcType=INTEGER}, ",
        "#{assignedCourseCount,jdbcType=INTEGER}, #{activeTeacherCountW,jdbcType=INTEGER}, ",
        "#{activeTeacherCountLw,jdbcType=INTEGER}, #{activeTeacherCountLlw,jdbcType=INTEGER}, ",
        "#{increStudent1d,jdbcType=INTEGER}, #{increPotentialStudent1d,jdbcType=INTEGER}, ",
        "#{increStudent7d,jdbcType=INTEGER}, #{increPotentialStudent7d,jdbcType=INTEGER}, ",
        "#{increStudent30d,jdbcType=INTEGER}, #{increPotentialStudent30d,jdbcType=INTEGER}, ",
        "#{newContract1d,jdbcType=INTEGER}, #{renewContract1d,jdbcType=INTEGER}, ",
        "#{contract1d,jdbcType=INTEGER}, #{newProfit1d,jdbcType=INTEGER}, ",
        "#{renewProfit1d,jdbcType=INTEGER}, #{profit1d,jdbcType=INTEGER}, ",
        "#{newContract7d,jdbcType=INTEGER}, #{renewContract7d,jdbcType=INTEGER}, ",
        "#{contract7d,jdbcType=INTEGER}, #{newProfit7d,jdbcType=INTEGER}, ",
        "#{renewProfit7d,jdbcType=INTEGER}, #{profit7d,jdbcType=INTEGER}, ",
        "#{newContract30d,jdbcType=INTEGER}, #{renewContract30d,jdbcType=INTEGER}, ",
        "#{contract30d,jdbcType=INTEGER}, #{newProfit30d,jdbcType=INTEGER}, ",
        "#{renewProfit30d,jdbcType=INTEGER}, #{profit30d,jdbcType=INTEGER}, ",
        "#{newContract6m,jdbcType=INTEGER}, #{renewContract6m,jdbcType=INTEGER}, ",
        "#{contract6m,jdbcType=INTEGER}, #{newProfit6m,jdbcType=INTEGER}, ",
        "#{renewProfit6m,jdbcType=INTEGER}, #{profit6m,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="instId", before=false, resultType=Long.class)
    int insert(InstStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @InsertProvider(type=InstStatsSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="instId", before=false, resultType=Long.class)
    int insertSelective(InstStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @SelectProvider(type=InstStatsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="inst_name", property="instName", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_count", property="studentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="potential_student_count", property="potentialStudentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="course_count", property="courseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="teacher_count", property="teacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="off_teacher_count", property="offTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="class_count", property="classCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_student_count", property="assignedStudentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_teacher_count", property="assignedTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_class_count", property="assignedClassCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_course_count", property="assignedCourseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_w", property="activeTeacherCountW", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_lw", property="activeTeacherCountLw", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_llw", property="activeTeacherCountLlw", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_1d", property="increStudent1d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_1d", property="increPotentialStudent1d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_7d", property="increStudent7d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_7d", property="increPotentialStudent7d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_30d", property="increStudent30d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_30d", property="increPotentialStudent30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_1d", property="newContract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_1d", property="renewContract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_1d", property="contract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_1d", property="newProfit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_1d", property="renewProfit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_1d", property="profit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_7d", property="newContract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_7d", property="renewContract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_7d", property="contract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_7d", property="newProfit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_7d", property="renewProfit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_7d", property="profit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_30d", property="newContract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_30d", property="renewContract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_30d", property="contract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_30d", property="newProfit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_30d", property="renewProfit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_30d", property="profit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_6m", property="newContract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_6m", property="renewContract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_6m", property="contract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_6m", property="newProfit6m", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_6m", property="renewProfit6m", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_6m", property="profit6m", jdbcType=JdbcType.INTEGER)
    })
    List<InstStats> selectByExample(InstStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @Select({
        "select",
        "inst_id, inst_name, student_count, potential_student_count, course_count, teacher_count, ",
        "off_teacher_count, class_count, assigned_student_count, assigned_teacher_count, ",
        "assigned_class_count, assigned_course_count, active_teacher_count_w, active_teacher_count_lw, ",
        "active_teacher_count_llw, incre_student_1d, incre_potential_student_1d, incre_student_7d, ",
        "incre_potential_student_7d, incre_student_30d, incre_potential_student_30d, ",
        "new_contract_1d, renew_contract_1d, contract_1d, new_profit_1d, renew_profit_1d, ",
        "profit_1d, new_contract_7d, renew_contract_7d, contract_7d, new_profit_7d, renew_profit_7d, ",
        "profit_7d, new_contract_30d, renew_contract_30d, contract_30d, new_profit_30d, ",
        "renew_profit_30d, profit_30d, new_contract_6m, renew_contract_6m, contract_6m, ",
        "new_profit_6m, renew_profit_6m, profit_6m",
        "from inst_stats",
        "where inst_id = #{instId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="inst_name", property="instName", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_count", property="studentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="potential_student_count", property="potentialStudentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="course_count", property="courseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="teacher_count", property="teacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="off_teacher_count", property="offTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="class_count", property="classCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_student_count", property="assignedStudentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_teacher_count", property="assignedTeacherCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_class_count", property="assignedClassCount", jdbcType=JdbcType.INTEGER),
        @Result(column="assigned_course_count", property="assignedCourseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_w", property="activeTeacherCountW", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_lw", property="activeTeacherCountLw", jdbcType=JdbcType.INTEGER),
        @Result(column="active_teacher_count_llw", property="activeTeacherCountLlw", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_1d", property="increStudent1d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_1d", property="increPotentialStudent1d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_7d", property="increStudent7d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_7d", property="increPotentialStudent7d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_student_30d", property="increStudent30d", jdbcType=JdbcType.INTEGER),
        @Result(column="incre_potential_student_30d", property="increPotentialStudent30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_1d", property="newContract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_1d", property="renewContract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_1d", property="contract1d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_1d", property="newProfit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_1d", property="renewProfit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_1d", property="profit1d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_7d", property="newContract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_7d", property="renewContract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_7d", property="contract7d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_7d", property="newProfit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_7d", property="renewProfit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_7d", property="profit7d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_30d", property="newContract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_30d", property="renewContract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_30d", property="contract30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_30d", property="newProfit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_30d", property="renewProfit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_30d", property="profit30d", jdbcType=JdbcType.INTEGER),
        @Result(column="new_contract_6m", property="newContract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_contract_6m", property="renewContract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="contract_6m", property="contract6m", jdbcType=JdbcType.INTEGER),
        @Result(column="new_profit_6m", property="newProfit6m", jdbcType=JdbcType.INTEGER),
        @Result(column="renew_profit_6m", property="renewProfit6m", jdbcType=JdbcType.INTEGER),
        @Result(column="profit_6m", property="profit6m", jdbcType=JdbcType.INTEGER)
    })
    InstStats selectByPrimaryKey(Long instId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @UpdateProvider(type=InstStatsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstStats record, @Param("example") InstStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @UpdateProvider(type=InstStatsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstStats record, @Param("example") InstStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @UpdateProvider(type=InstStatsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InstStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_stats
     *
     * @mbggenerated Sat Apr 22 13:55:51 CST 2017
     */
    @Update({
        "update inst_stats",
        "set inst_name = #{instName,jdbcType=VARCHAR},",
          "student_count = #{studentCount,jdbcType=INTEGER},",
          "potential_student_count = #{potentialStudentCount,jdbcType=INTEGER},",
          "course_count = #{courseCount,jdbcType=INTEGER},",
          "teacher_count = #{teacherCount,jdbcType=INTEGER},",
          "off_teacher_count = #{offTeacherCount,jdbcType=INTEGER},",
          "class_count = #{classCount,jdbcType=INTEGER},",
          "assigned_student_count = #{assignedStudentCount,jdbcType=INTEGER},",
          "assigned_teacher_count = #{assignedTeacherCount,jdbcType=INTEGER},",
          "assigned_class_count = #{assignedClassCount,jdbcType=INTEGER},",
          "assigned_course_count = #{assignedCourseCount,jdbcType=INTEGER},",
          "active_teacher_count_w = #{activeTeacherCountW,jdbcType=INTEGER},",
          "active_teacher_count_lw = #{activeTeacherCountLw,jdbcType=INTEGER},",
          "active_teacher_count_llw = #{activeTeacherCountLlw,jdbcType=INTEGER},",
          "incre_student_1d = #{increStudent1d,jdbcType=INTEGER},",
          "incre_potential_student_1d = #{increPotentialStudent1d,jdbcType=INTEGER},",
          "incre_student_7d = #{increStudent7d,jdbcType=INTEGER},",
          "incre_potential_student_7d = #{increPotentialStudent7d,jdbcType=INTEGER},",
          "incre_student_30d = #{increStudent30d,jdbcType=INTEGER},",
          "incre_potential_student_30d = #{increPotentialStudent30d,jdbcType=INTEGER},",
          "new_contract_1d = #{newContract1d,jdbcType=INTEGER},",
          "renew_contract_1d = #{renewContract1d,jdbcType=INTEGER},",
          "contract_1d = #{contract1d,jdbcType=INTEGER},",
          "new_profit_1d = #{newProfit1d,jdbcType=INTEGER},",
          "renew_profit_1d = #{renewProfit1d,jdbcType=INTEGER},",
          "profit_1d = #{profit1d,jdbcType=INTEGER},",
          "new_contract_7d = #{newContract7d,jdbcType=INTEGER},",
          "renew_contract_7d = #{renewContract7d,jdbcType=INTEGER},",
          "contract_7d = #{contract7d,jdbcType=INTEGER},",
          "new_profit_7d = #{newProfit7d,jdbcType=INTEGER},",
          "renew_profit_7d = #{renewProfit7d,jdbcType=INTEGER},",
          "profit_7d = #{profit7d,jdbcType=INTEGER},",
          "new_contract_30d = #{newContract30d,jdbcType=INTEGER},",
          "renew_contract_30d = #{renewContract30d,jdbcType=INTEGER},",
          "contract_30d = #{contract30d,jdbcType=INTEGER},",
          "new_profit_30d = #{newProfit30d,jdbcType=INTEGER},",
          "renew_profit_30d = #{renewProfit30d,jdbcType=INTEGER},",
          "profit_30d = #{profit30d,jdbcType=INTEGER},",
          "new_contract_6m = #{newContract6m,jdbcType=INTEGER},",
          "renew_contract_6m = #{renewContract6m,jdbcType=INTEGER},",
          "contract_6m = #{contract6m,jdbcType=INTEGER},",
          "new_profit_6m = #{newProfit6m,jdbcType=INTEGER},",
          "renew_profit_6m = #{renewProfit6m,jdbcType=INTEGER},",
          "profit_6m = #{profit6m,jdbcType=INTEGER}",
        "where inst_id = #{instId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(InstStats record);
}