package com.jiejing.dao2.stat;

import com.jiejing.model.InstScoreTeacherHistory;
import com.jiejing.model.InstScoreTeacherHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstScoreTeacherHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @SelectProvider(type=InstScoreTeacherHistorySqlProvider.class, method="countByExample")
    int countByExample(InstScoreTeacherHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @DeleteProvider(type=InstScoreTeacherHistorySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstScoreTeacherHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @Insert({
        "insert into inst_score_teacher_history (inst_id, count, ",
        "sum_score, score, ",
        "teacher_id)",
        "values (#{instId,jdbcType=BIGINT}, #{count,jdbcType=INTEGER}, ",
        "#{sumScore,jdbcType=INTEGER}, #{score,jdbcType=DOUBLE}, ",
        "#{teacherId,jdbcType=BIGINT})"
    })
    int insert(InstScoreTeacherHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @InsertProvider(type=InstScoreTeacherHistorySqlProvider.class, method="insertSelective")
    int insertSelective(InstScoreTeacherHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @SelectProvider(type=InstScoreTeacherHistorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="sum_score", property="sumScore", jdbcType=JdbcType.INTEGER),
        @Result(column="score", property="score", jdbcType=JdbcType.DOUBLE),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.BIGINT)
    })
    List<InstScoreTeacherHistory> selectByExample(InstScoreTeacherHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @UpdateProvider(type=InstScoreTeacherHistorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstScoreTeacherHistory record, @Param("example") InstScoreTeacherHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_teacher_history
     *
     * @mbggenerated Mon Apr 17 20:25:21 CST 2017
     */
    @UpdateProvider(type=InstScoreTeacherHistorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstScoreTeacherHistory record, @Param("example") InstScoreTeacherHistoryExample example);
}