package com.jiejing.dao2.stat;

import com.jiejing.model.InstClassHourCourseTeacherDaily;
import com.jiejing.model.InstClassHourCourseTeacherDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstClassHourCourseTeacherDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @SelectProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="countByExample")
    int countByExample(InstClassHourCourseTeacherDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @DeleteProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstClassHourCourseTeacherDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @Insert({
        "insert into inst_class_hour_course_teacher_daily (inst_id, course_id, ",
        "teacher_id, class_hour, ",
        "price, type, day)",
        "values (#{instId,jdbcType=BIGINT}, #{courseId,jdbcType=BIGINT}, ",
        "#{teacherId,jdbcType=BIGINT}, #{classHour,jdbcType=BIGINT}, ",
        "#{price,jdbcType=BIGINT}, #{type,jdbcType=BIGINT}, #{day,jdbcType=DATE})"
    })
    int insert(InstClassHourCourseTeacherDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @InsertProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="insertSelective")
    int insertSelective(InstClassHourCourseTeacherDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @SelectProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.BIGINT),
        @Result(column="class_hour", property="classHour", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.BIGINT),
        @Result(column="day", property="day", jdbcType=JdbcType.DATE)
    })
    List<InstClassHourCourseTeacherDaily> selectByExample(InstClassHourCourseTeacherDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @UpdateProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstClassHourCourseTeacherDaily record, @Param("example") InstClassHourCourseTeacherDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_class_hour_course_teacher_daily
     *
     * @mbggenerated Thu Apr 13 10:26:58 CST 2017
     */
    @UpdateProvider(type=InstClassHourCourseTeacherDailySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstClassHourCourseTeacherDaily record, @Param("example") InstClassHourCourseTeacherDailyExample example);
}