package com.jiejing.dao2.stat;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.jiejing.model.InstContractCourseMonthly;
import com.jiejing.model.InstContractCourseMonthlyExample.Criteria;
import com.jiejing.model.InstContractCourseMonthlyExample.Criterion;
import com.jiejing.model.InstContractCourseMonthlyExample;
import java.util.List;
import java.util.Map;

public class InstContractCourseMonthlySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String countByExample(InstContractCourseMonthlyExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("inst_contract_course_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String deleteByExample(InstContractCourseMonthlyExample example) {
        BEGIN();
        DELETE_FROM("inst_contract_course_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String insertSelective(InstContractCourseMonthly record) {
        BEGIN();
        INSERT_INTO("inst_contract_course_monthly");
        
        if (record.getInstId() != null) {
            VALUES("inst_id", "#{instId,jdbcType=BIGINT}");
        }
        
        if (record.getInstName() != null) {
            VALUES("inst_name", "#{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getYear() != null) {
            VALUES("year", "#{year,jdbcType=INTEGER}");
        }
        
        if (record.getMonth() != null) {
            VALUES("month", "#{month,jdbcType=INTEGER}");
        }
        
        if (record.getYearmonth() != null) {
            VALUES("yearmonth", "#{yearmonth,jdbcType=INTEGER}");
        }
        
        if (record.getCourseId() != null) {
            VALUES("course_id", "#{courseId,jdbcType=BIGINT}");
        }
        
        if (record.getCourseName() != null) {
            VALUES("course_name", "#{courseName,jdbcType=VARCHAR}");
        }
        
        if (record.getCountNew() != null) {
            VALUES("count_new", "#{countNew,jdbcType=INTEGER}");
        }
        
        if (record.getCountCont() != null) {
            VALUES("count_cont", "#{countCont,jdbcType=INTEGER}");
        }
        
        if (record.getProfitNew() != null) {
            VALUES("profit_new", "#{profitNew,jdbcType=INTEGER}");
        }
        
        if (record.getProfitCont() != null) {
            VALUES("profit_cont", "#{profitCont,jdbcType=INTEGER}");
        }
        
        if (record.getRenewRate() != null) {
            VALUES("renew_rate", "#{renewRate,jdbcType=DOUBLE}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String selectByExample(InstContractCourseMonthlyExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("inst_id");
        } else {
            SELECT("inst_id");
        }
        SELECT("inst_name");
        SELECT("year");
        SELECT("month");
        SELECT("yearmonth");
        SELECT("course_id");
        SELECT("course_name");
        SELECT("count_new");
        SELECT("count_cont");
        SELECT("profit_new");
        SELECT("profit_cont");
        SELECT("renew_rate");
        FROM("inst_contract_course_monthly");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return SQL() + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        InstContractCourseMonthly record = (InstContractCourseMonthly) parameter.get("record");
        InstContractCourseMonthlyExample example = (InstContractCourseMonthlyExample) parameter.get("example");
        
        BEGIN();
        UPDATE("inst_contract_course_monthly");
        
        if (record.getInstId() != null) {
            SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        }
        
        if (record.getInstName() != null) {
            SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        }
        
        if (record.getYear() != null) {
            SET("year = #{record.year,jdbcType=INTEGER}");
        }
        
        if (record.getMonth() != null) {
            SET("month = #{record.month,jdbcType=INTEGER}");
        }
        
        if (record.getYearmonth() != null) {
            SET("yearmonth = #{record.yearmonth,jdbcType=INTEGER}");
        }
        
        if (record.getCourseId() != null) {
            SET("course_id = #{record.courseId,jdbcType=BIGINT}");
        }
        
        if (record.getCourseName() != null) {
            SET("course_name = #{record.courseName,jdbcType=VARCHAR}");
        }
        
        if (record.getCountNew() != null) {
            SET("count_new = #{record.countNew,jdbcType=INTEGER}");
        }
        
        if (record.getCountCont() != null) {
            SET("count_cont = #{record.countCont,jdbcType=INTEGER}");
        }
        
        if (record.getProfitNew() != null) {
            SET("profit_new = #{record.profitNew,jdbcType=INTEGER}");
        }
        
        if (record.getProfitCont() != null) {
            SET("profit_cont = #{record.profitCont,jdbcType=INTEGER}");
        }
        
        if (record.getRenewRate() != null) {
            SET("renew_rate = #{record.renewRate,jdbcType=DOUBLE}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("inst_contract_course_monthly");
        
        SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        SET("year = #{record.year,jdbcType=INTEGER}");
        SET("month = #{record.month,jdbcType=INTEGER}");
        SET("yearmonth = #{record.yearmonth,jdbcType=INTEGER}");
        SET("course_id = #{record.courseId,jdbcType=BIGINT}");
        SET("course_name = #{record.courseName,jdbcType=VARCHAR}");
        SET("count_new = #{record.countNew,jdbcType=INTEGER}");
        SET("count_cont = #{record.countCont,jdbcType=INTEGER}");
        SET("profit_new = #{record.profitNew,jdbcType=INTEGER}");
        SET("profit_cont = #{record.profitCont,jdbcType=INTEGER}");
        SET("renew_rate = #{record.renewRate,jdbcType=DOUBLE}");
        
        InstContractCourseMonthlyExample example = (InstContractCourseMonthlyExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_contract_course_monthly
     *
     * @mbggenerated Thu Apr 20 18:02:28 CST 2017
     */
    protected void applyWhere(InstContractCourseMonthlyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}