package com.jiejing.dao2.stat;

import com.jiejing.model.InstScoreCourseHistory;
import com.jiejing.model.InstScoreCourseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InstScoreCourseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @SelectProvider(type=InstScoreCourseHistorySqlProvider.class, method="countByExample")
    int countByExample(InstScoreCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @DeleteProvider(type=InstScoreCourseHistorySqlProvider.class, method="deleteByExample")
    int deleteByExample(InstScoreCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @Insert({
        "insert into inst_score_course_history (inst_id, count, ",
        "sum_score, score, ",
        "course_id)",
        "values (#{instId,jdbcType=BIGINT}, #{count,jdbcType=INTEGER}, ",
        "#{sumScore,jdbcType=INTEGER}, #{score,jdbcType=DOUBLE}, ",
        "#{courseId,jdbcType=BIGINT})"
    })
    int insert(InstScoreCourseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @InsertProvider(type=InstScoreCourseHistorySqlProvider.class, method="insertSelective")
    int insertSelective(InstScoreCourseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @SelectProvider(type=InstScoreCourseHistorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="sum_score", property="sumScore", jdbcType=JdbcType.INTEGER),
        @Result(column="score", property="score", jdbcType=JdbcType.DOUBLE),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT)
    })
    List<InstScoreCourseHistory> selectByExample(InstScoreCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @UpdateProvider(type=InstScoreCourseHistorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") InstScoreCourseHistory record, @Param("example") InstScoreCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inst_score_course_history
     *
     * @mbggenerated Tue Apr 18 09:54:09 CST 2017
     */
    @UpdateProvider(type=InstScoreCourseHistorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") InstScoreCourseHistory record, @Param("example") InstScoreCourseHistoryExample example);
}