package com.jiejing.dao2.stat;

import com.jiejing.model.MstatFinanEarningActual;
import com.jiejing.model.MstatFinanEarningActualExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MstatFinanEarningActualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int countByExample(MstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int deleteByExample(MstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insert(MstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insertSelective(MstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    List<MstatFinanEarningActual> selectByExample(MstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatFinanEarningActual record, @Param("example") MstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatFinanEarningActual record, @Param("example") MstatFinanEarningActualExample example);

    List<Map> selectGroupByType(@Param("instIds") List<Long> instIds,
                                @Param("monthStart") Date monthStart);


    List<Map> selectGroupBySource(@Param("instIds") List<Long> instIds,
                                  @Param("monthStart") Date monthStart);
}