package com.jiejing.dao2.stat;

import com.jiejing.model.MstatTeachingAttendanceInstDetail;
import com.jiejing.model.MstatTeachingAttendanceInstDetailExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.jiejing.vo.AttendanceItemVO;
import org.apache.ibatis.annotations.Param;

public interface MstatTeachingAttendanceInstDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int countByExample(MstatTeachingAttendanceInstDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int deleteByExample(MstatTeachingAttendanceInstDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int insert(MstatTeachingAttendanceInstDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int insertSelective(MstatTeachingAttendanceInstDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    List<MstatTeachingAttendanceInstDetail> selectByExample(MstatTeachingAttendanceInstDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    MstatTeachingAttendanceInstDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatTeachingAttendanceInstDetail record, @Param("example") MstatTeachingAttendanceInstDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatTeachingAttendanceInstDetail record, @Param("example") MstatTeachingAttendanceInstDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MstatTeachingAttendanceInstDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MstatTeachingAttendanceInstDetail record);

    List<Map> selectListByExampleGroupByCourse(@Param("instId") Long instId,
                                               @Param("begin") Long beign,
                                               @Param("end") Long end,
                                               @Param("offset") Integer offset,
                                               @Param("limit") Integer limit);

    int countByExampleGroupByCourse(@Param("instId") Long instId,
                                    @Param("begin") Long beign,
                                    @Param("end") Long end);
}