package com.jiejing.dao2.stat;

import com.jiejing.model.MstatSaleContract;
import com.jiejing.model.MstatSaleContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatSaleContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int countByExample(MstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int deleteByExample(MstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int insert(MstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int insertSelective(MstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    List<MstatSaleContract> selectByExample(MstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatSaleContract record, @Param("example") MstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatSaleContract record, @Param("example") MstatSaleContractExample example);
}