package com.jiejing.dao2.stat;

import com.jiejing.model.MstatStudentDelta;
import com.jiejing.model.MstatStudentDeltaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatStudentDeltaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int countByExample(MstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int deleteByExample(MstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int insert(MstatStudentDelta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int insertSelective(MstatStudentDelta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    List<MstatStudentDelta> selectByExample(MstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatStudentDelta record, @Param("example") MstatStudentDeltaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_delta
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatStudentDelta record, @Param("example") MstatStudentDeltaExample example);
}