package com.jiejing.dao2.stat;

import com.jiejing.model.MstatFinanExpense;
import com.jiejing.model.MstatFinanExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatFinanExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int countByExample(MstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByExample(MstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int insert(MstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int insertSelective(MstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    List<MstatFinanExpense> selectByExample(MstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    MstatFinanExpense selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatFinanExpense record, @Param("example") MstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatFinanExpense record, @Param("example") MstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MstatFinanExpense record);

    void batchInsert(@Param("items") List<MstatFinanExpense> items);
}