package com.jiejing.dao2.stat;

import com.jiejing.model.MstatTeachingClasshourTeacher;
import com.jiejing.model.MstatTeachingClasshourTeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatTeachingClasshourTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int countByExample(MstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int deleteByExample(MstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int insert(MstatTeachingClasshourTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int insertSelective(MstatTeachingClasshourTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    List<MstatTeachingClasshourTeacher> selectByExample(MstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatTeachingClasshourTeacher record, @Param("example") MstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatTeachingClasshourTeacher record, @Param("example") MstatTeachingClasshourTeacherExample example);

    void batchInsert(@Param("items") List<MstatTeachingClasshourTeacher> items);
}