package com.jiejing.dao2.stat;

import com.jiejing.model.MstatTeachingAttendanceInst;
import com.jiejing.model.MstatTeachingAttendanceInstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatTeachingAttendanceInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int countByExample(MstatTeachingAttendanceInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int deleteByExample(MstatTeachingAttendanceInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int insert(MstatTeachingAttendanceInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int insertSelective(MstatTeachingAttendanceInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    List<MstatTeachingAttendanceInst> selectByExample(MstatTeachingAttendanceInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    MstatTeachingAttendanceInst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatTeachingAttendanceInst record, @Param("example") MstatTeachingAttendanceInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatTeachingAttendanceInst record, @Param("example") MstatTeachingAttendanceInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MstatTeachingAttendanceInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_attendance_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MstatTeachingAttendanceInst record);
}