package com.jiejing.dao2.stat;

import com.jiejing.model.MstatTeachingScoreInst;
import com.jiejing.model.MstatTeachingScoreInstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatTeachingScoreInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int countByExample(MstatTeachingScoreInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int deleteByExample(MstatTeachingScoreInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int insert(MstatTeachingScoreInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int insertSelective(MstatTeachingScoreInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    List<MstatTeachingScoreInst> selectByExample(MstatTeachingScoreInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatTeachingScoreInst record, @Param("example") MstatTeachingScoreInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_teaching_score_inst
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatTeachingScoreInst record, @Param("example") MstatTeachingScoreInstExample example);
}