package com.jiejing.dao2.stat;

import com.jiejing.model.MstatStudentLostDistrib;
import com.jiejing.model.MstatStudentLostDistribExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstatStudentLostDistribMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int countByExample(MstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int deleteByExample(MstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int insert(MstatStudentLostDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int insertSelective(MstatStudentLostDistrib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    List<MstatStudentLostDistrib> selectByExample(MstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MstatStudentLostDistrib record, @Param("example") MstatStudentLostDistribExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mstat_student_lost_distrib
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MstatStudentLostDistrib record, @Param("example") MstatStudentLostDistribExample example);
}