package com.jiejing.dao2.stat;

import com.jiejing.model.StatInstClassOccupancyMonthly;
import com.jiejing.model.StatInstClassOccupancyMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StatInstClassOccupancyMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @SelectProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="countByExample")
    int countByExample(StatInstClassOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @DeleteProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(StatInstClassOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @Insert({
        "insert into stat_inst_class_occupancy_monthly (snap_month, class_id, ",
        "class_name, course_id, ",
        "course_name, inst_id, ",
        "inst_name, class_capacity, ",
        "student_count, class_occupancy)",
        "values (#{snapMonth,jdbcType=INTEGER}, #{classId,jdbcType=BIGINT}, ",
        "#{className,jdbcType=VARCHAR}, #{courseId,jdbcType=BIGINT}, ",
        "#{courseName,jdbcType=VARCHAR}, #{instId,jdbcType=BIGINT}, ",
        "#{instName,jdbcType=VARCHAR}, #{classCapacity,jdbcType=BIGINT}, ",
        "#{studentCount,jdbcType=INTEGER}, #{classOccupancy,jdbcType=DOUBLE})"
    })
    int insert(StatInstClassOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @InsertProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(StatInstClassOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @SelectProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="snap_month", property="snapMonth", jdbcType=JdbcType.INTEGER),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.BIGINT),
        @Result(column="class_name", property="className", jdbcType=JdbcType.VARCHAR),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_name", property="courseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="inst_name", property="instName", jdbcType=JdbcType.VARCHAR),
        @Result(column="class_capacity", property="classCapacity", jdbcType=JdbcType.BIGINT),
        @Result(column="student_count", property="studentCount", jdbcType=JdbcType.INTEGER),
        @Result(column="class_occupancy", property="classOccupancy", jdbcType=JdbcType.DOUBLE)
    })
    List<StatInstClassOccupancyMonthly> selectByExample(StatInstClassOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @UpdateProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StatInstClassOccupancyMonthly record, @Param("example") StatInstClassOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_class_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:44:32 CST 2017
     */
    @UpdateProvider(type=StatInstClassOccupancyMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StatInstClassOccupancyMonthly record, @Param("example") StatInstClassOccupancyMonthlyExample example);
}