package com.jiejing.dao2.stat;

import com.jiejing.model.StatInstOccupancyMonthly;
import com.jiejing.model.StatInstOccupancyMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StatInstOccupancyMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @SelectProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="countByExample")
    int countByExample(StatInstOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @DeleteProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(StatInstOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @Insert({
        "insert into stat_inst_occupancy_monthly (inst_id, inst_name, ",
        "snap_month, class_occupancy)",
        "values (#{instId,jdbcType=BIGINT}, #{instName,jdbcType=VARCHAR}, ",
        "#{snapMonth,jdbcType=INTEGER}, #{classOccupancy,jdbcType=DOUBLE})"
    })
    int insert(StatInstOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @InsertProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(StatInstOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @SelectProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="inst_name", property="instName", jdbcType=JdbcType.VARCHAR),
        @Result(column="snap_month", property="snapMonth", jdbcType=JdbcType.INTEGER),
        @Result(column="class_occupancy", property="classOccupancy", jdbcType=JdbcType.DOUBLE)
    })
    List<StatInstOccupancyMonthly> selectByExample(StatInstOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @UpdateProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StatInstOccupancyMonthly record, @Param("example") StatInstOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 16:45:00 CST 2017
     */
    @UpdateProvider(type=StatInstOccupancyMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StatInstOccupancyMonthly record, @Param("example") StatInstOccupancyMonthlyExample example);
}