package com.jiejing.dao2.stat;

import com.jiejing.model.StatInstCourseOccupancyMonthly;
import com.jiejing.model.StatInstCourseOccupancyMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StatInstCourseOccupancyMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @SelectProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="countByExample")
    int countByExample(StatInstCourseOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @DeleteProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="deleteByExample")
    int deleteByExample(StatInstCourseOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @Insert({
        "insert into stat_inst_course_occupancy_monthly (class_count, inst_id, ",
        "inst_name, course_id, ",
        "course_name, snap_month, ",
        "class_capacity, student_count, ",
        "class_occupancy)",
        "values (#{classCount,jdbcType=BIGINT}, #{instId,jdbcType=BIGINT}, ",
        "#{instName,jdbcType=VARCHAR}, #{courseId,jdbcType=BIGINT}, ",
        "#{courseName,jdbcType=VARCHAR}, #{snapMonth,jdbcType=INTEGER}, ",
        "#{classCapacity,jdbcType=BIGINT}, #{studentCount,jdbcType=BIGINT}, ",
        "#{classOccupancy,jdbcType=DOUBLE})"
    })
    int insert(StatInstCourseOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @InsertProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="insertSelective")
    int insertSelective(StatInstCourseOccupancyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @SelectProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="class_count", property="classCount", jdbcType=JdbcType.BIGINT),
        @Result(column="inst_id", property="instId", jdbcType=JdbcType.BIGINT),
        @Result(column="inst_name", property="instName", jdbcType=JdbcType.VARCHAR),
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="course_name", property="courseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="snap_month", property="snapMonth", jdbcType=JdbcType.INTEGER),
        @Result(column="class_capacity", property="classCapacity", jdbcType=JdbcType.BIGINT),
        @Result(column="student_count", property="studentCount", jdbcType=JdbcType.BIGINT),
        @Result(column="class_occupancy", property="classOccupancy", jdbcType=JdbcType.DOUBLE)
    })
    List<StatInstCourseOccupancyMonthly> selectByExample(StatInstCourseOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @UpdateProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StatInstCourseOccupancyMonthly record, @Param("example") StatInstCourseOccupancyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_course_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:27 CST 2017
     */
    @UpdateProvider(type=StatInstCourseOccupancyMonthlySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StatInstCourseOccupancyMonthly record, @Param("example") StatInstCourseOccupancyMonthlyExample example);
}