package com.jiejing.dao2.stat;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.jiejing.model.StatInstTeacherOccupancyMonthly;
import com.jiejing.model.StatInstTeacherOccupancyMonthlyExample.Criteria;
import com.jiejing.model.StatInstTeacherOccupancyMonthlyExample.Criterion;
import com.jiejing.model.StatInstTeacherOccupancyMonthlyExample;
import java.util.List;
import java.util.Map;

public class StatInstTeacherOccupancyMonthlySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String countByExample(StatInstTeacherOccupancyMonthlyExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("stat_inst_teacher_occupancy_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String deleteByExample(StatInstTeacherOccupancyMonthlyExample example) {
        BEGIN();
        DELETE_FROM("stat_inst_teacher_occupancy_monthly");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String insertSelective(StatInstTeacherOccupancyMonthly record) {
        BEGIN();
        INSERT_INTO("stat_inst_teacher_occupancy_monthly");
        
        if (record.getClassCount() != null) {
            VALUES("class_count", "#{classCount,jdbcType=BIGINT}");
        }
        
        if (record.getSnapMonth() != null) {
            VALUES("snap_month", "#{snapMonth,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherId() != null) {
            VALUES("teacher_id", "#{teacherId,jdbcType=BIGINT}");
        }
        
        if (record.getTeacherName() != null) {
            VALUES("teacher_name", "#{teacherName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstId() != null) {
            VALUES("inst_id", "#{instId,jdbcType=BIGINT}");
        }
        
        if (record.getInstName() != null) {
            VALUES("inst_name", "#{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getClassCapacity() != null) {
            VALUES("class_capacity", "#{classCapacity,jdbcType=BIGINT}");
        }
        
        if (record.getStudentCount() != null) {
            VALUES("student_count", "#{studentCount,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherOccupancy() != null) {
            VALUES("teacher_occupancy", "#{teacherOccupancy,jdbcType=DOUBLE}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String selectByExample(StatInstTeacherOccupancyMonthlyExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("class_count");
        } else {
            SELECT("class_count");
        }
        SELECT("snap_month");
        SELECT("teacher_id");
        SELECT("teacher_name");
        SELECT("inst_id");
        SELECT("inst_name");
        SELECT("class_capacity");
        SELECT("student_count");
        SELECT("teacher_occupancy");
        FROM("stat_inst_teacher_occupancy_monthly");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return SQL() + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        StatInstTeacherOccupancyMonthly record = (StatInstTeacherOccupancyMonthly) parameter.get("record");
        StatInstTeacherOccupancyMonthlyExample example = (StatInstTeacherOccupancyMonthlyExample) parameter.get("example");
        
        BEGIN();
        UPDATE("stat_inst_teacher_occupancy_monthly");
        
        if (record.getClassCount() != null) {
            SET("class_count = #{record.classCount,jdbcType=BIGINT}");
        }
        
        if (record.getSnapMonth() != null) {
            SET("snap_month = #{record.snapMonth,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherId() != null) {
            SET("teacher_id = #{record.teacherId,jdbcType=BIGINT}");
        }
        
        if (record.getTeacherName() != null) {
            SET("teacher_name = #{record.teacherName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstId() != null) {
            SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        }
        
        if (record.getInstName() != null) {
            SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        }
        
        if (record.getClassCapacity() != null) {
            SET("class_capacity = #{record.classCapacity,jdbcType=BIGINT}");
        }
        
        if (record.getStudentCount() != null) {
            SET("student_count = #{record.studentCount,jdbcType=INTEGER}");
        }
        
        if (record.getTeacherOccupancy() != null) {
            SET("teacher_occupancy = #{record.teacherOccupancy,jdbcType=DOUBLE}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("stat_inst_teacher_occupancy_monthly");
        
        SET("class_count = #{record.classCount,jdbcType=BIGINT}");
        SET("snap_month = #{record.snapMonth,jdbcType=INTEGER}");
        SET("teacher_id = #{record.teacherId,jdbcType=BIGINT}");
        SET("teacher_name = #{record.teacherName,jdbcType=VARCHAR}");
        SET("inst_id = #{record.instId,jdbcType=BIGINT}");
        SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        SET("class_capacity = #{record.classCapacity,jdbcType=BIGINT}");
        SET("student_count = #{record.studentCount,jdbcType=INTEGER}");
        SET("teacher_occupancy = #{record.teacherOccupancy,jdbcType=DOUBLE}");
        
        StatInstTeacherOccupancyMonthlyExample example = (StatInstTeacherOccupancyMonthlyExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_inst_teacher_occupancy_monthly
     *
     * @mbggenerated Fri Apr 21 17:56:18 CST 2017
     */
    protected void applyWhere(StatInstTeacherOccupancyMonthlyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}