package com.jiejing.dao2.stat;

import com.jiejing.model.WstatFinanEarning;
import com.jiejing.model.WstatFinanEarningExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WstatFinanEarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int countByExample(WstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int deleteByExample(WstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int insert(WstatFinanEarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int insertSelective(WstatFinanEarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    List<WstatFinanEarning> selectByExample(WstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatFinanEarning record, @Param("example") WstatFinanEarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatFinanEarning record, @Param("example") WstatFinanEarningExample example);

    void batchInsert(@Param("items") List<WstatFinanEarning> items);

}