package com.jiejing.dao2.stat;

import com.jiejing.model.WstatSaleContract;
import com.jiejing.model.WstatSaleContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WstatSaleContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int countByExample(WstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int deleteByExample(WstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int insert(WstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int insertSelective(WstatSaleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    List<WstatSaleContract> selectByExample(WstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatSaleContract record, @Param("example") WstatSaleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_sale_contract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatSaleContract record, @Param("example") WstatSaleContractExample example);
}