package com.jiejing.dao2.stat;

import com.jiejing.model.WstatFinanExpense;
import com.jiejing.model.WstatFinanExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WstatFinanExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int countByExample(WstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByExample(WstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int insert(WstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int insertSelective(WstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    List<WstatFinanExpense> selectByExample(WstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    WstatFinanExpense selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatFinanExpense record, @Param("example") WstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatFinanExpense record, @Param("example") WstatFinanExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WstatFinanExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WstatFinanExpense record);

    void batchInsert(@Param("items") List<WstatFinanExpense> items);
}