package com.jiejing.dao2.stat;

import com.jiejing.model.WstatTeachingClasshourInst;
import com.jiejing.model.WstatTeachingClasshourInstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WstatTeachingClasshourInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int countByExample(WstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int deleteByExample(WstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int insert(WstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int insertSelective(WstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    List<WstatTeachingClasshourInst> selectByExample(WstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    WstatTeachingClasshourInst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatTeachingClasshourInst record, @Param("example") WstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatTeachingClasshourInst record, @Param("example") WstatTeachingClasshourInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WstatTeachingClasshourInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_inst
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WstatTeachingClasshourInst record);

    void batchInsert(@Param("items") List<WstatTeachingClasshourInst> items);
}