package com.jiejing.dao2.stat;

import com.jiejing.model.WstatTeachingClasshourTeacher;
import com.jiejing.model.WstatTeachingClasshourTeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WstatTeachingClasshourTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int countByExample(WstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int deleteByExample(WstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int insert(WstatTeachingClasshourTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int insertSelective(WstatTeachingClasshourTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    List<WstatTeachingClasshourTeacher> selectByExample(WstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatTeachingClasshourTeacher record, @Param("example") WstatTeachingClasshourTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_teaching_classhour_teacher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatTeachingClasshourTeacher record, @Param("example") WstatTeachingClasshourTeacherExample example);
}