package com.jiejing.dao2.stat;

import com.jiejing.model.WstatFinanEarningActual;
import com.jiejing.model.WstatFinanEarningActualExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface WstatFinanEarningActualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int countByExample(WstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int deleteByExample(WstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insert(WstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int insertSelective(WstatFinanEarningActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    List<WstatFinanEarningActual> selectByExample(WstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WstatFinanEarningActual record, @Param("example") WstatFinanEarningActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstat_finan_earning_actual
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WstatFinanEarningActual record, @Param("example") WstatFinanEarningActualExample example);

    List<Map> selectGroupByType(@Param("instIds") List<Long> instIds,
                                @Param("weekStart") Date weekStart);

    List<Map> selectGroupBySource(@Param("instIds") List<Long> instIds,
                                  @Param("weekStart") Date weekStart);
}