package com.jiejing.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@Builder
@NoArgsConstructor
public class InstitutionClassSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.inst_id
     *
     * @mbggenerated
     */
    private Long instId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.class_id
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.class_status
     *
     * @mbggenerated
     */
    private Integer classStatus;

//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column institution_class_schedule.teacher_id
//     *
//     * @mbggenerated
//     */
//    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.teacher_name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.start_minute
     *
     * @mbggenerated
     */
    private Integer startMinute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.end_minute
     *
     * @mbggenerated
     */
    private Integer endMinute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.step
     *
     * @mbggenerated
     */
    private Integer step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.trial_student_ids
     *
     * @mbggenerated
     */
    @Deprecated
    private String trialStudentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.week
     *
     * @mbggenerated
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.loop_time
     *
     * @mbggenerated
     */
    private Integer loopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.schedule_type
     *
     * @mbggenerated
     */
    private Integer scheduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.sign_id
     *
     * @mbggenerated
     */
    private String signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.batch_id
     *
     * @mbggenerated
     */
    private Long batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.sign_date
     *
     * @mbggenerated
     */
    private Date signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.sign_status
     *
     * @mbggenerated
     */
    private Integer signStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.split_flag
     *
     * @mbggenerated
     */
    private Integer splitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.temp_status
     *
     * @mbggenerated
     */
    private Integer tempStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.sign_schedule_id
     *
     * @mbggenerated
     */
    private Long signScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.teacher_ids
     *
     * @mbggenerated
     */
    private String teacherIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.class_room_id
     *
     * @mbggenerated
     */
    private Long classRoomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution_class_schedule.class_room_name
     *
     * @mbggenerated
     */
    private String classRoomName;

    public Boolean isOneTime() {
        return scheduleType != null && scheduleType.equals(1);
    }
}