package com.jiejing.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InstitutionClassScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected boolean forUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public InstitutionClassScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public boolean isForUpdate() {
        return forUpdate;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andInstIdIsNull() {
            addCriterion("inst_id is null");
            return (Criteria) this;
        }

        public Criteria andInstIdIsNotNull() {
            addCriterion("inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andInstIdEqualTo(Long value) {
            addCriterion("inst_id =", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotEqualTo(Long value) {
            addCriterion("inst_id <>", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThan(Long value) {
            addCriterion("inst_id >", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThanOrEqualTo(Long value) {
            addCriterion("inst_id >=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThan(Long value) {
            addCriterion("inst_id <", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThanOrEqualTo(Long value) {
            addCriterion("inst_id <=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdIn(List<Long> values) {
            addCriterion("inst_id in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotIn(List<Long> values) {
            addCriterion("inst_id not in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdBetween(Long value1, Long value2) {
            addCriterion("inst_id between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotBetween(Long value1, Long value2) {
            addCriterion("inst_id not between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Long value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Long value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Long value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Long value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Long value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Long value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Long> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Long> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Long value1, Long value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Long value1, Long value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassStatusIsNull() {
            addCriterion("class_status is null");
            return (Criteria) this;
        }

        public Criteria andClassStatusIsNotNull() {
            addCriterion("class_status is not null");
            return (Criteria) this;
        }

        public Criteria andClassStatusEqualTo(Integer value) {
            addCriterion("class_status =", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotEqualTo(Integer value) {
            addCriterion("class_status <>", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusGreaterThan(Integer value) {
            addCriterion("class_status >", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_status >=", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusLessThan(Integer value) {
            addCriterion("class_status <", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusLessThanOrEqualTo(Integer value) {
            addCriterion("class_status <=", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusIn(List<Integer> values) {
            addCriterion("class_status in", values, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotIn(List<Integer> values) {
            addCriterion("class_status not in", values, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusBetween(Integer value1, Integer value2) {
            addCriterion("class_status between", value1, value2, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("class_status not between", value1, value2, "classStatus");
            return (Criteria) this;
        }

//        public Criteria andTeacherIdIsNull() {
//            addCriterion("teacher_id is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdIsNotNull() {
//            addCriterion("teacher_id is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdEqualTo(Long value) {
//            addCriterion("teacher_id =", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdNotEqualTo(Long value) {
//            addCriterion("teacher_id <>", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdGreaterThan(Long value) {
//            addCriterion("teacher_id >", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdGreaterThanOrEqualTo(Long value) {
//            addCriterion("teacher_id >=", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdLessThan(Long value) {
//            addCriterion("teacher_id <", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdLessThanOrEqualTo(Long value) {
//            addCriterion("teacher_id <=", value, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdIn(List<Long> values) {
//            addCriterion("teacher_id in", values, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdNotIn(List<Long> values) {
//            addCriterion("teacher_id not in", values, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdBetween(Long value1, Long value2) {
//            addCriterion("teacher_id between", value1, value2, "teacherId");
//            return (Criteria) this;
//        }
//
//        public Criteria andTeacherIdNotBetween(Long value1, Long value2) {
//            addCriterion("teacher_id not between", value1, value2, "teacherId");
//            return (Criteria) this;
//        }

        public Criteria andTeacherNameIsNull() {
            addCriterion("teacher_name is null");
            return (Criteria) this;
        }

        public Criteria andTeacherNameIsNotNull() {
            addCriterion("teacher_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherNameEqualTo(String value) {
            addCriterion("teacher_name =", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotEqualTo(String value) {
            addCriterion("teacher_name <>", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameGreaterThan(String value) {
            addCriterion("teacher_name >", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_name >=", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLessThan(String value) {
            addCriterion("teacher_name <", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLessThanOrEqualTo(String value) {
            addCriterion("teacher_name <=", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLike(String value) {
            addCriterion("teacher_name like", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotLike(String value) {
            addCriterion("teacher_name not like", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameIn(List<String> values) {
            addCriterion("teacher_name in", values, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotIn(List<String> values) {
            addCriterion("teacher_name not in", values, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameBetween(String value1, String value2) {
            addCriterion("teacher_name between", value1, value2, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotBetween(String value1, String value2) {
            addCriterion("teacher_name not between", value1, value2, "teacherName");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNull() {
            addCriterion("begin_date is null");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNotNull() {
            addCriterion("begin_date is not null");
            return (Criteria) this;
        }

        public Criteria andBeginDateEqualTo(Date value) {
            addCriterion("begin_date =", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotEqualTo(Date value) {
            addCriterion("begin_date <>", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThan(Date value) {
            addCriterion("begin_date >", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_date >=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThan(Date value) {
            addCriterion("begin_date <", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThanOrEqualTo(Date value) {
            addCriterion("begin_date <=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateIn(List<Date> values) {
            addCriterion("begin_date in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotIn(List<Date> values) {
            addCriterion("begin_date not in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateBetween(Date value1, Date value2) {
            addCriterion("begin_date between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotBetween(Date value1, Date value2) {
            addCriterion("begin_date not between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andStartMinuteIsNull() {
            addCriterion("start_minute is null");
            return (Criteria) this;
        }

        public Criteria andStartMinuteIsNotNull() {
            addCriterion("start_minute is not null");
            return (Criteria) this;
        }

        public Criteria andStartMinuteEqualTo(Integer value) {
            addCriterion("start_minute =", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteNotEqualTo(Integer value) {
            addCriterion("start_minute <>", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteGreaterThan(Integer value) {
            addCriterion("start_minute >", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("start_minute >=", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteLessThan(Integer value) {
            addCriterion("start_minute <", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("start_minute <=", value, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteIn(List<Integer> values) {
            addCriterion("start_minute in", values, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteNotIn(List<Integer> values) {
            addCriterion("start_minute not in", values, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteBetween(Integer value1, Integer value2) {
            addCriterion("start_minute between", value1, value2, "startMinute");
            return (Criteria) this;
        }

        public Criteria andStartMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("start_minute not between", value1, value2, "startMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteIsNull() {
            addCriterion("end_minute is null");
            return (Criteria) this;
        }

        public Criteria andEndMinuteIsNotNull() {
            addCriterion("end_minute is not null");
            return (Criteria) this;
        }

        public Criteria andEndMinuteEqualTo(Integer value) {
            addCriterion("end_minute =", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteNotEqualTo(Integer value) {
            addCriterion("end_minute <>", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteGreaterThan(Integer value) {
            addCriterion("end_minute >", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_minute >=", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteLessThan(Integer value) {
            addCriterion("end_minute <", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("end_minute <=", value, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteIn(List<Integer> values) {
            addCriterion("end_minute in", values, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteNotIn(List<Integer> values) {
            addCriterion("end_minute not in", values, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteBetween(Integer value1, Integer value2) {
            addCriterion("end_minute between", value1, value2, "endMinute");
            return (Criteria) this;
        }

        public Criteria andEndMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("end_minute not between", value1, value2, "endMinute");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(Integer value) {
            addCriterion("step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(Integer value) {
            addCriterion("step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(Integer value) {
            addCriterion("step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(Integer value) {
            addCriterion("step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(Integer value) {
            addCriterion("step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<Integer> values) {
            addCriterion("step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<Integer> values) {
            addCriterion("step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(Integer value1, Integer value2) {
            addCriterion("step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(Integer value1, Integer value2) {
            addCriterion("step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNull() {
            addCriterion("gmt_modify is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNotNull() {
            addCriterion("gmt_modify is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyEqualTo(Date value) {
            addCriterion("gmt_modify =", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotEqualTo(Date value) {
            addCriterion("gmt_modify <>", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThan(Date value) {
            addCriterion("gmt_modify >", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modify >=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThan(Date value) {
            addCriterion("gmt_modify <", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modify <=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIn(List<Date> values) {
            addCriterion("gmt_modify in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotIn(List<Date> values) {
            addCriterion("gmt_modify not in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyBetween(Date value1, Date value2) {
            addCriterion("gmt_modify between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modify not between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsIsNull() {
            addCriterion("trial_student_ids is null");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsIsNotNull() {
            addCriterion("trial_student_ids is not null");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsEqualTo(String value) {
            addCriterion("trial_student_ids =", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsNotEqualTo(String value) {
            addCriterion("trial_student_ids <>", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsGreaterThan(String value) {
            addCriterion("trial_student_ids >", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsGreaterThanOrEqualTo(String value) {
            addCriterion("trial_student_ids >=", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsLessThan(String value) {
            addCriterion("trial_student_ids <", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsLessThanOrEqualTo(String value) {
            addCriterion("trial_student_ids <=", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsLike(String value) {
            addCriterion("trial_student_ids like", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsNotLike(String value) {
            addCriterion("trial_student_ids not like", value, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsIn(List<String> values) {
            addCriterion("trial_student_ids in", values, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsNotIn(List<String> values) {
            addCriterion("trial_student_ids not in", values, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsBetween(String value1, String value2) {
            addCriterion("trial_student_ids between", value1, value2, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andTrialStudentIdsNotBetween(String value1, String value2) {
            addCriterion("trial_student_ids not between", value1, value2, "trialStudentIds");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(Integer value) {
            addCriterion("week =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(Integer value) {
            addCriterion("week <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(Integer value) {
            addCriterion("week >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("week >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(Integer value) {
            addCriterion("week <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(Integer value) {
            addCriterion("week <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<Integer> values) {
            addCriterion("week in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<Integer> values) {
            addCriterion("week not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(Integer value1, Integer value2) {
            addCriterion("week between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("week not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andLoopTimeIsNull() {
            addCriterion("loop_time is null");
            return (Criteria) this;
        }

        public Criteria andLoopTimeIsNotNull() {
            addCriterion("loop_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoopTimeEqualTo(Integer value) {
            addCriterion("loop_time =", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeNotEqualTo(Integer value) {
            addCriterion("loop_time <>", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeGreaterThan(Integer value) {
            addCriterion("loop_time >", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("loop_time >=", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeLessThan(Integer value) {
            addCriterion("loop_time <", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeLessThanOrEqualTo(Integer value) {
            addCriterion("loop_time <=", value, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeIn(List<Integer> values) {
            addCriterion("loop_time in", values, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeNotIn(List<Integer> values) {
            addCriterion("loop_time not in", values, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeBetween(Integer value1, Integer value2) {
            addCriterion("loop_time between", value1, value2, "loopTime");
            return (Criteria) this;
        }

        public Criteria andLoopTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("loop_time not between", value1, value2, "loopTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNull() {
            addCriterion("schedule_type is null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNotNull() {
            addCriterion("schedule_type is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeEqualTo(Integer value) {
            addCriterion("schedule_type =", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotEqualTo(Integer value) {
            addCriterion("schedule_type <>", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThan(Integer value) {
            addCriterion("schedule_type >", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_type >=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThan(Integer value) {
            addCriterion("schedule_type <", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_type <=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIn(List<Integer> values) {
            addCriterion("schedule_type in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotIn(List<Integer> values) {
            addCriterion("schedule_type not in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeBetween(Integer value1, Integer value2) {
            addCriterion("schedule_type between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_type not between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andSignIdIsNull() {
            addCriterion("sign_id is null");
            return (Criteria) this;
        }

        public Criteria andSignIdIsNotNull() {
            addCriterion("sign_id is not null");
            return (Criteria) this;
        }

        public Criteria andSignIdEqualTo(String value) {
            addCriterion("sign_id =", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdNotEqualTo(String value) {
            addCriterion("sign_id <>", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdGreaterThan(String value) {
            addCriterion("sign_id >", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdGreaterThanOrEqualTo(String value) {
            addCriterion("sign_id >=", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdLessThan(String value) {
            addCriterion("sign_id <", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdLessThanOrEqualTo(String value) {
            addCriterion("sign_id <=", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdLike(String value) {
            addCriterion("sign_id like", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdNotLike(String value) {
            addCriterion("sign_id not like", value, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdIn(List<String> values) {
            addCriterion("sign_id in", values, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdNotIn(List<String> values) {
            addCriterion("sign_id not in", values, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdBetween(String value1, String value2) {
            addCriterion("sign_id between", value1, value2, "signId");
            return (Criteria) this;
        }

        public Criteria andSignIdNotBetween(String value1, String value2) {
            addCriterion("sign_id not between", value1, value2, "signId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("batch_id is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("batch_id is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(Long value) {
            addCriterion("batch_id =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(Long value) {
            addCriterion("batch_id <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(Long value) {
            addCriterion("batch_id >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(Long value) {
            addCriterion("batch_id >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(Long value) {
            addCriterion("batch_id <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(Long value) {
            addCriterion("batch_id <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<Long> values) {
            addCriterion("batch_id in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<Long> values) {
            addCriterion("batch_id not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(Long value1, Long value2) {
            addCriterion("batch_id between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(Long value1, Long value2) {
            addCriterion("batch_id not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNull() {
            addCriterion("sign_date is null");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNotNull() {
            addCriterion("sign_date is not null");
            return (Criteria) this;
        }

        public Criteria andSignDateEqualTo(Date value) {
            addCriterion("sign_date =", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotEqualTo(Date value) {
            addCriterion("sign_date <>", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThan(Date value) {
            addCriterion("sign_date >", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThanOrEqualTo(Date value) {
            addCriterion("sign_date >=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThan(Date value) {
            addCriterion("sign_date <", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThanOrEqualTo(Date value) {
            addCriterion("sign_date <=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateIn(List<Date> values) {
            addCriterion("sign_date in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotIn(List<Date> values) {
            addCriterion("sign_date not in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateBetween(Date value1, Date value2) {
            addCriterion("sign_date between", value1, value2, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotBetween(Date value1, Date value2) {
            addCriterion("sign_date not between", value1, value2, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignStatusIsNull() {
            addCriterion("sign_status is null");
            return (Criteria) this;
        }

        public Criteria andSignStatusIsNotNull() {
            addCriterion("sign_status is not null");
            return (Criteria) this;
        }

        public Criteria andSignStatusEqualTo(Integer value) {
            addCriterion("sign_status =", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusNotEqualTo(Integer value) {
            addCriterion("sign_status <>", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusGreaterThan(Integer value) {
            addCriterion("sign_status >", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_status >=", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusLessThan(Integer value) {
            addCriterion("sign_status <", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sign_status <=", value, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusIn(List<Integer> values) {
            addCriterion("sign_status in", values, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusNotIn(List<Integer> values) {
            addCriterion("sign_status not in", values, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusBetween(Integer value1, Integer value2) {
            addCriterion("sign_status between", value1, value2, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSignStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_status not between", value1, value2, "signStatus");
            return (Criteria) this;
        }

        public Criteria andSplitFlagIsNull() {
            addCriterion("split_flag is null");
            return (Criteria) this;
        }

        public Criteria andSplitFlagIsNotNull() {
            addCriterion("split_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSplitFlagEqualTo(Integer value) {
            addCriterion("split_flag =", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagNotEqualTo(Integer value) {
            addCriterion("split_flag <>", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagGreaterThan(Integer value) {
            addCriterion("split_flag >", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("split_flag >=", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagLessThan(Integer value) {
            addCriterion("split_flag <", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagLessThanOrEqualTo(Integer value) {
            addCriterion("split_flag <=", value, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagIn(List<Integer> values) {
            addCriterion("split_flag in", values, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagNotIn(List<Integer> values) {
            addCriterion("split_flag not in", values, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagBetween(Integer value1, Integer value2) {
            addCriterion("split_flag between", value1, value2, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andSplitFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("split_flag not between", value1, value2, "splitFlag");
            return (Criteria) this;
        }

        public Criteria andTempStatusIsNull() {
            addCriterion("temp_status is null");
            return (Criteria) this;
        }

        public Criteria andTempStatusIsNotNull() {
            addCriterion("temp_status is not null");
            return (Criteria) this;
        }

        public Criteria andTempStatusEqualTo(Integer value) {
            addCriterion("temp_status =", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusNotEqualTo(Integer value) {
            addCriterion("temp_status <>", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusGreaterThan(Integer value) {
            addCriterion("temp_status >", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_status >=", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusLessThan(Integer value) {
            addCriterion("temp_status <", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusLessThanOrEqualTo(Integer value) {
            addCriterion("temp_status <=", value, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusIn(List<Integer> values) {
            addCriterion("temp_status in", values, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusNotIn(List<Integer> values) {
            addCriterion("temp_status not in", values, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusBetween(Integer value1, Integer value2) {
            addCriterion("temp_status between", value1, value2, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andTempStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_status not between", value1, value2, "tempStatus");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdIsNull() {
            addCriterion("sign_schedule_id is null");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdIsNotNull() {
            addCriterion("sign_schedule_id is not null");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdEqualTo(Long value) {
            addCriterion("sign_schedule_id =", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdNotEqualTo(Long value) {
            addCriterion("sign_schedule_id <>", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdGreaterThan(Long value) {
            addCriterion("sign_schedule_id >", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sign_schedule_id >=", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdLessThan(Long value) {
            addCriterion("sign_schedule_id <", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdLessThanOrEqualTo(Long value) {
            addCriterion("sign_schedule_id <=", value, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdIn(List<Long> values) {
            addCriterion("sign_schedule_id in", values, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdNotIn(List<Long> values) {
            addCriterion("sign_schedule_id not in", values, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdBetween(Long value1, Long value2) {
            addCriterion("sign_schedule_id between", value1, value2, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andSignScheduleIdNotBetween(Long value1, Long value2) {
            addCriterion("sign_schedule_id not between", value1, value2, "signScheduleId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsIsNull() {
            addCriterion("teacher_ids is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsIsNotNull() {
            addCriterion("teacher_ids is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsEqualTo(String value) {
            addCriterion("teacher_ids =", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsNotEqualTo(String value) {
            addCriterion("teacher_ids <>", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsGreaterThan(String value) {
            addCriterion("teacher_ids >", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_ids >=", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsLessThan(String value) {
            addCriterion("teacher_ids <", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsLessThanOrEqualTo(String value) {
            addCriterion("teacher_ids <=", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsLike(String value) {
            addCriterion("teacher_ids like", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsNotLike(String value) {
            addCriterion("teacher_ids not like", value, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsIn(List<Long> values) {
            addCriterion("teacher_ids in", values, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsNotIn(List<String> values) {
            addCriterion("teacher_ids not in", values, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsBetween(String value1, String value2) {
            addCriterion("teacher_ids between", value1, value2, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andTeacherIdsNotBetween(String value1, String value2) {
            addCriterion("teacher_ids not between", value1, value2, "teacherIds");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdIsNull() {
            addCriterion("class_room_id is null");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdIsNotNull() {
            addCriterion("class_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdEqualTo(Long value) {
            addCriterion("class_room_id =", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdNotEqualTo(Long value) {
            addCriterion("class_room_id <>", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdGreaterThan(Long value) {
            addCriterion("class_room_id >", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdGreaterThanOrEqualTo(Long value) {
            addCriterion("class_room_id >=", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdLessThan(Long value) {
            addCriterion("class_room_id <", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdLessThanOrEqualTo(Long value) {
            addCriterion("class_room_id <=", value, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdIn(List<Long> values) {
            addCriterion("class_room_id in", values, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdNotIn(List<Long> values) {
            addCriterion("class_room_id not in", values, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdBetween(Long value1, Long value2) {
            addCriterion("class_room_id between", value1, value2, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomIdNotBetween(Long value1, Long value2) {
            addCriterion("class_room_id not between", value1, value2, "classRoomId");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameIsNull() {
            addCriterion("class_room_name is null");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameIsNotNull() {
            addCriterion("class_room_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameEqualTo(String value) {
            addCriterion("class_room_name =", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameNotEqualTo(String value) {
            addCriterion("class_room_name <>", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameGreaterThan(String value) {
            addCriterion("class_room_name >", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_room_name >=", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameLessThan(String value) {
            addCriterion("class_room_name <", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameLessThanOrEqualTo(String value) {
            addCriterion("class_room_name <=", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameLike(String value) {
            addCriterion("class_room_name like", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameNotLike(String value) {
            addCriterion("class_room_name not like", value, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameIn(List<String> values) {
            addCriterion("class_room_name in", values, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameNotIn(List<String> values) {
            addCriterion("class_room_name not in", values, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameBetween(String value1, String value2) {
            addCriterion("class_room_name between", value1, value2, "classRoomName");
            return (Criteria) this;
        }

        public Criteria andClassRoomNameNotBetween(String value1, String value2) {
            addCriterion("class_room_name not between", value1, value2, "classRoomName");
            return (Criteria) this;
        }
        /**
        * This method was generated by MyBatis Generator.
        * This method corresponds to the database table institution_class_schedule
        *
        * @mbggenerated Sat Jul 30 18:39:59 CST 2017
        */
        public Criteria addConditionSql(String conditionSql) {
            addCriterion(conditionSql);
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_class_schedule
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_class_schedule
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}