spring:
  application:
    name: jwt-auth-service
  redis:
    host: localhost
    port: 6379

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
