eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8084
zuul:
  routes:
    service-compute: /compute/**
    feign-service: /feign/**