security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8082/oauth/token
      userAuthorizationUri: http://localhost:8082/oauth/authorize
      clientId: client_1
      clientSecret: 123456
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user